// Code generated by "go run -C ../generate ./cmd/generate/"; DO NOT EDIT.

package attr

// Special attributes

// AriaProp
// Element(s): Global attribute.
// Description: Sets aria-* properties.
// Value: Text.
func AriaProp(property, value string) *AttributeStruct {
	return Attr("aria-" + property, value)
}

// DataProp
// Element(s): Global attribute.
// Description: Lets you attach custom attributes to an HTML element.
// Value: Text.
func DataProp(property, value string) *AttributeStruct {
	return Attr("data-" + property, value)
}

// Role
// Element(s): Global attribute.
// Description: Defines an explicit role for an element for use by assistive technologies.
// Value: Text.
func Role(value string) *AttributeStruct {
	return Attr("role", value)
}

// Regular Attributes

// Itemtype 
// Element(s): HTML elements.
// Description: Item types of a microdata item.
// Value: Unordered set of unique space-separated tokens consisting of valid absolute URLs*.
func Itemtype(value string) *AttributeStruct {
	return Attr("itemtype", value)
}

// Minlength 
// Element(s): input; textarea.
// Description: Minimum length of value.
// Value: Valid non-negative integer.
func Minlength(value string) *AttributeStruct {
	return Attr("minlength", value)
}

// HttpEquiv 
// Element(s): meta.
// Description: Pragma directive.
// Value: "content-type"; "default-style"; "refresh"; "x-ua-compatible"; "content-security-policy".
func HttpEquiv(value string) *AttributeStruct {
	return Attr("http-equiv", value)
}

// Pattern 
// Element(s): input.
// Description: Pattern to be matched by the form control's value.
// Value: Regular expression matching the JavaScript Pattern production.
func Pattern(value string) *AttributeStruct {
	return Attr("pattern", value)
}

// Cite 
// Element(s): blockquote; del; ins; q.
// Description: Link to the source of the quotation or more information about the edit.
// Value: Valid URL potentially surrounded by spaces.
func Cite(value string) *AttributeStruct {
	return Attr("cite", value)
}

// Preload 
// Element(s): audio; video.
// Description: Hints how much buffering the media resource will likely need.
// Value: "none"; "metadata"; "auto".
func Preload(value string) *AttributeStruct {
	return Attr("preload", value)
}

// Shadowrootmode 
// Element(s): template.
// Description: Enables streaming declarative shadow roots.
// Value: "open"; "closed".
func Shadowrootmode(value string) *AttributeStruct {
	return Attr("shadowrootmode", value)
}

// Srcset 
// Element(s): img; source.
// Description: Images to use in different situations, e.g., high-resolution displays, small monitors, etc..
// Value: Comma-separated list of image candidate strings.
func Srcset(value string) *AttributeStruct {
	return Attr("srcset", value)
}

// Allow 
// Element(s): iframe.
// Description: Permissions policy to be applied to the iframe's contents.
// Value: Serialized permissions policy.
func Allow(value string) *AttributeStruct {
	return Attr("allow", value)
}

// Class 
// Element(s): HTML elements.
// Description: Classes to which the element belongs.
// Value: Set of space-separated tokens.
func Class(value string) *AttributeStruct {
	return Attr("class", value)
}

// Command 
// Element(s): button.
// Description: Indicates to the targeted element which action to take..
// Value: "toggle-popover"; "show-popover"; "hide-popover"; "close"; "show-modal"; a custom command keyword.
func Command(value string) *AttributeStruct {
	return Attr("command", value)
}

// Loading 
// Element(s): iframe; img.
// Description: Used when determining loading deferral.
// Value: "lazy"; "eager".
func Loading(value string) *AttributeStruct {
	return Attr("loading", value)
}

// Spellcheck 
// Element(s): HTML elements.
// Description: Whether the element is to have its spelling and grammar checked.
// Value: "true"; "false"; the empty string.
func Spellcheck(value string) *AttributeStruct {
	return Attr("spellcheck", value)
}

// Abbr 
// Element(s): th.
// Description: Alternative label to use for the header cell when referencing the cell in other contexts.
// Value: Text*.
func Abbr(value string) *AttributeStruct {
	return Attr("abbr", value)
}

// Accept 
// Element(s): input.
// Description: Hint for expected file type in file upload controls.
// Value: Set of comma-separated tokens* consisting of valid MIME type strings with no parameters or audio/*, video/*, or image/*.
func Accept(value string) *AttributeStruct {
	return Attr("accept", value)
}

// Content 
// Element(s): meta.
// Description: Value of the element.
// Value: Text*.
func Content(value string) *AttributeStruct {
	return Attr("content", value)
}

// Novalidate 
// Element(s): form.
// Description: Bypass form control validation for form submission.
// Value: Boolean attribute.
func Novalidate(value bool) *AttributeStruct {
	return BooleanAttr("novalidate", value)
}

// Popovertarget 
// Element(s): button; input.
// Description: Targets a popover element to toggle, show, or hide.
// Value: ID*.
func Popovertarget(value string) *AttributeStruct {
	return Attr("popovertarget", value)
}

// Async 
// Element(s): script.
// Description: Execute script when available, without blocking while fetching.
// Value: Boolean attribute.
func Async(value bool) *AttributeStruct {
	return BooleanAttr("async", value)
}

// Itemref 
// Element(s): HTML elements.
// Description: Referenced elements.
// Value: Unordered set of unique space-separated tokens consisting of IDs*.
func Itemref(value string) *AttributeStruct {
	return Attr("itemref", value)
}

// Placeholder 
// Element(s): input; textarea.
// Description: User-visible label to be placed within the form control.
// Value: Text*.
func Placeholder(value string) *AttributeStruct {
	return Attr("placeholder", value)
}

// Rowspan 
// Element(s): td; th.
// Description: Number of rows that the cell is to span.
// Value: Valid non-negative integer.
func Rowspan(value string) *AttributeStruct {
	return Attr("rowspan", value)
}

// Src 
// Element(s): audio; embed; iframe; img; input; script; source (in video or audio); track; video.
// Description: Address of the resource.
// Value: Valid non-empty URL potentially surrounded by spaces.
func Src(value string) *AttributeStruct {
	return Attr("src", value)
}

// Colorspace 
// Element(s): input.
// Description: The color space of the serialized color.
// Value: "limited-srgb"; "display-p3".
func Colorspace(value string) *AttributeStruct {
	return Attr("colorspace", value)
}

// Enterkeyhint 
// Element(s): HTML elements.
// Description: Hint for selecting an enter key action.
// Value: "enter"; "done"; "go"; "next"; "previous"; "search"; "send".
func Enterkeyhint(value string) *AttributeStruct {
	return Attr("enterkeyhint", value)
}

// Formnovalidate 
// Element(s): button; input.
// Description: Bypass form control validation for form submission.
// Value: Boolean attribute.
func Formnovalidate(value bool) *AttributeStruct {
	return BooleanAttr("formnovalidate", value)
}

// High 
// Element(s): meter.
// Description: Low limit of high range.
// Value: Valid floating-point number*.
func High(value string) *AttributeStruct {
	return Attr("high", value)
}

// Sandbox 
// Element(s): iframe.
// Description: Security rules for nested content.
// Value: Unordered set of unique space-separated tokens, ASCII case-insensitive, consisting of "allow-downloads""allow-forms""allow-modals""allow-orientation-lock""allow-pointer-lock""allow-popups""allow-popups-to-escape-sandbox""allow-presentation""allow-same-origin""allow-scripts""allow-top-navigation""allow-top-navigation-by-user-activation""allow-top-navigation-to-custom-protocols".
func Sandbox(value string) *AttributeStruct {
	return Attr("sandbox", value)
}

// Formaction 
// Element(s): button; input.
// Description: URL to use for form submission.
// Value: Valid non-empty URL potentially surrounded by spaces.
func Formaction(value string) *AttributeStruct {
	return Attr("formaction", value)
}

// Height 
// Element(s): canvas; embed; iframe; img; input; object; source (in picture); video.
// Description: Vertical dimension.
// Value: Valid non-negative integer.
func Height(value string) *AttributeStruct {
	return Attr("height", value)
}

// Is 
// Element(s): HTML elements.
// Description: Creates a customized built-in element.
// Value: Valid custom element name of a defined customized built-in element.
func Is(value string) *AttributeStruct {
	return Attr("is", value)
}

// Media 
// Element(s): link; meta; source; style.
// Description: Applicable media.
// Value: Valid media query list.
func Media(value string) *AttributeStruct {
	return Attr("media", value)
}

// Method 
// Element(s): form.
// Description: Variant to use for form submission.
// Value: "GET"; "POST"; "dialog".
func Method(value string) *AttributeStruct {
	return Attr("method", value)
}

// Popovertargetaction 
// Element(s): button; input.
// Description: Indicates whether a targeted popover element is to be toggled, shown, or hidden.
// Value: "toggle"; "show"; "hide".
func Popovertargetaction(value string) *AttributeStruct {
	return Attr("popovertargetaction", value)
}

// Alpha 
// Element(s): input.
// Description: Allow the color's alpha component to be set.
// Value: Boolean attribute.
func Alpha(value bool) *AttributeStruct {
	return BooleanAttr("alpha", value)
}

// Autoplay 
// Element(s): audio; video.
// Description: Hint that the media resource can be started automatically when the page is loaded.
// Value: Boolean attribute.
func Autoplay(value bool) *AttributeStruct {
	return BooleanAttr("autoplay", value)
}

// Form 
// Element(s): button; fieldset; input; object; output; select; textarea; form-associated custom elements.
// Description: Associates the element with a form element.
// Value: ID*.
func Form(value string) *AttributeStruct {
	return Attr("form", value)
}

// Hreflang 
// Element(s): a; link.
// Description: Language of the linked resource.
// Value: Valid BCP 47 language tag.
func Hreflang(value string) *AttributeStruct {
	return Attr("hreflang", value)
}

// Itemprop 
// Element(s): HTML elements.
// Description: Property names of a microdata item.
// Value: Unordered set of unique space-separated tokens consisting of valid absolute URLs, defined property names, or text*.
func Itemprop(value string) *AttributeStruct {
	return Attr("itemprop", value)
}

// Style 
// Element(s): HTML elements.
// Description: Presentational and formatting instructions.
// Value: CSS declarations*.
func Style(value string) *AttributeStruct {
	return Attr("style", value)
}

// As 
// Element(s): link.
// Description: Potential destination for a preload request (for rel="preload" and rel="modulepreload").
// Value: Potential destination, for rel="preload"; script-like destination, for rel="modulepreload".
func As(value string) *AttributeStruct {
	return Attr("as", value)
}

// Contenteditable 
// Element(s): HTML elements.
// Description: Whether the element is editable.
// Value: "true"; "plaintext-only"; "false".
func Contenteditable(value string) *AttributeStruct {
	return Attr("contenteditable", value)
}

// Defer 
// Element(s): script.
// Description: Defer script execution.
// Value: Boolean attribute.
func Defer(value bool) *AttributeStruct {
	return BooleanAttr("defer", value)
}

// Integrity 
// Element(s): link; script.
// Description: Integrity metadata used in Subresource Integrity checks [SRI].
// Value: Text.
func Integrity(value string) *AttributeStruct {
	return Attr("integrity", value)
}

// Low 
// Element(s): meter.
// Description: High limit of low range.
// Value: Valid floating-point number*.
func Low(value string) *AttributeStruct {
	return Attr("low", value)
}

// Autocomplete 
// Element(s): form.
// Description: Default setting for autofill feature for controls in the form.
// Value: "on"; "off".
//
// Element(s): input; select; textarea.
// Description: Hint for form autofill feature.
// Value: Autofill field name and related tokens*.
func Autocomplete(value string) *AttributeStruct {
	return Attr("autocomplete", value)
}

// Muted 
// Element(s): audio; video.
// Description: Whether to mute the media resource by default.
// Value: Boolean attribute.
func Muted(value bool) *AttributeStruct {
	return BooleanAttr("muted", value)
}

// Optimum 
// Element(s): meter.
// Description: Optimum value in gauge.
// Value: Valid floating-point number*.
func Optimum(value string) *AttributeStruct {
	return Attr("optimum", value)
}

// Data 
// Element(s): object.
// Description: Address of the resource.
// Value: Valid non-empty URL potentially surrounded by spaces.
func Data(value string) *AttributeStruct {
	return Attr("data", value)
}

// Rows 
// Element(s): textarea.
// Description: Number of lines to show.
// Value: Valid non-negative integer greater than zero.
func Rows(value string) *AttributeStruct {
	return Attr("rows", value)
}

// Type 
// Element(s): a; link.
// Description: Hint for the type of the referenced resource.
// Value: Valid MIME type string.
//
// Element(s): button.
// Description: Type of button.
// Value: "submit"; "reset"; "button".
//
// Element(s): embed; object; source.
// Description: Type of embedded resource.
// Value: Valid MIME type string.
//
// Element(s): input.
// Description: Type of form control.
// Value: input type keyword.
//
// Element(s): ol.
// Description: Kind of list marker.
// Value: "1"; "a"; "A"; "i"; "I".
//
// Element(s): script.
// Description: Type of script.
// Value: "module"; a valid MIME type string that is not a JavaScript MIME type essence match.
func Type(value string) *AttributeStruct {
	return Attr("type", value)
}

// Sizes 
// Element(s): link.
// Description: Sizes of the icons (for rel="icon").
// Value: Unordered set of unique space-separated tokens, ASCII case-insensitive, consisting of sizes*.
//
// Element(s): img; source.
// Description: Image sizes for different page layouts.
// Value: Valid source size list.
func Sizes(value string) *AttributeStruct {
	return Attr("sizes", value)
}

// Controls 
// Element(s): audio; video.
// Description: Show user agent controls.
// Value: Boolean attribute.
func Controls(value bool) *AttributeStruct {
	return BooleanAttr("controls", value)
}

// Hidden 
// Element(s): HTML elements.
// Description: Whether the element is relevant.
// Value: "until-found"; "hidden"; the empty string.
func Hidden(value string) *AttributeStruct {
	return Attr("hidden", value)
}

// Href 
// Element(s): a; area.
// Description: Address of the hyperlink.
// Value: Valid URL potentially surrounded by spaces.
//
// Element(s): link.
// Description: Address of the hyperlink.
// Value: Valid non-empty URL potentially surrounded by spaces.
//
// Element(s): base.
// Description: Document base URL.
// Value: Valid URL potentially surrounded by spaces.
func Href(value string) *AttributeStruct {
	return Attr("href", value)
}

// Nonce 
// Element(s): HTML elements.
// Description: Cryptographic nonce used in Content Security Policy checks [CSP].
// Value: Text.
func Nonce(value string) *AttributeStruct {
	return Attr("nonce", value)
}

// Scope 
// Element(s): th.
// Description: Specifies which cells the header cell applies to.
// Value: "row"; "col"; "rowgroup"; "colgroup".
func Scope(value string) *AttributeStruct {
	return Attr("scope", value)
}

// Cols 
// Element(s): textarea.
// Description: Maximum number of characters per line.
// Value: Valid non-negative integer greater than zero.
func Cols(value string) *AttributeStruct {
	return Attr("cols", value)
}

// Commandfor 
// Element(s): button.
// Description: Targets another element to be invoked..
// Value: ID*.
func Commandfor(value string) *AttributeStruct {
	return Attr("commandfor", value)
}

// Poster 
// Element(s): video.
// Description: Poster frame to show prior to video playback.
// Value: Valid non-empty URL potentially surrounded by spaces.
func Poster(value string) *AttributeStruct {
	return Attr("poster", value)
}

// Reversed 
// Element(s): ol.
// Description: Number the list backwards.
// Value: Boolean attribute.
func Reversed(value bool) *AttributeStruct {
	return BooleanAttr("reversed", value)
}

// Size 
// Element(s): input; select.
// Description: Size of the control.
// Value: Valid non-negative integer greater than zero.
func Size(value string) *AttributeStruct {
	return Attr("size", value)
}

// Autocapitalize 
// Element(s): HTML elements.
// Description: Recommended autocapitalization behavior (for supported input methods).
// Value: "on"; "off"; "none"; "sentences"; "words"; "characters".
func Autocapitalize(value string) *AttributeStruct {
	return Attr("autocapitalize", value)
}

// Id 
// Element(s): HTML elements.
// Description: The element's ID.
// Value: Text*.
func Id(value string) *AttributeStruct {
	return Attr("id", value)
}

// Ping 
// Element(s): a; area.
// Description: URLs to ping.
// Value: Set of space-separated tokens consisting of valid non-empty URLs.
func Ping(value string) *AttributeStruct {
	return Attr("ping", value)
}

// Width 
// Element(s): canvas; embed; iframe; img; input; object; source (in picture); video.
// Description: Horizontal dimension.
// Value: Valid non-negative integer.
func Width(value string) *AttributeStruct {
	return Attr("width", value)
}

// Action 
// Element(s): form.
// Description: URL to use for form submission.
// Value: Valid non-empty URL potentially surrounded by spaces.
func Action(value string) *AttributeStruct {
	return Attr("action", value)
}

// Closedby 
// Element(s): dialog.
// Description: Which user actions will close the dialog.
// Value: "any"; "closerequest"; "none";.
func Closedby(value string) *AttributeStruct {
	return Attr("closedby", value)
}

// Headers 
// Element(s): td; th.
// Description: The header cells for this cell.
// Value: Unordered set of unique space-separated tokens consisting of IDs*.
func Headers(value string) *AttributeStruct {
	return Attr("headers", value)
}

// Step 
// Element(s): input.
// Description: Granularity to be matched by the form control's value.
// Value: Valid floating-point number greater than zero, or "any".
func Step(value string) *AttributeStruct {
	return Attr("step", value)
}

// Writingsuggestions 
// Element(s): HTML elements.
// Description: Whether the element can offer writing suggestions or not..
// Value: "true"; "false"; the empty string.
func Writingsuggestions(value string) *AttributeStruct {
	return Attr("writingsuggestions", value)
}

// Draggable 
// Element(s): HTML elements.
// Description: Whether the element is draggable.
// Value: "true"; "false".
func Draggable(value string) *AttributeStruct {
	return Attr("draggable", value)
}

// Itemid 
// Element(s): HTML elements.
// Description: Global identifier for a microdata item.
// Value: Valid URL potentially surrounded by spaces.
func Itemid(value string) *AttributeStruct {
	return Attr("itemid", value)
}

// Target 
// Element(s): a; area.
// Description: Navigable for hyperlink navigation.
// Value: Valid navigable target name or keyword.
//
// Element(s): base.
// Description: Default navigable for hyperlink navigation and form submission.
// Value: Valid navigable target name or keyword.
//
// Element(s): form.
// Description: Navigable for form submission.
// Value: Valid navigable target name or keyword.
func Target(value string) *AttributeStruct {
	return Attr("target", value)
}

// Inert 
// Element(s): HTML elements.
// Description: Whether the element is inert..
// Value: Boolean attribute.
func Inert(value bool) *AttributeStruct {
	return BooleanAttr("inert", value)
}

// Multiple 
// Element(s): input; select.
// Description: Whether to allow multiple values.
// Value: Boolean attribute.
func Multiple(value bool) *AttributeStruct {
	return BooleanAttr("multiple", value)
}

// Slot 
// Element(s): HTML elements.
// Description: The element's desired slot.
// Value: Text.
func Slot(value string) *AttributeStruct {
	return Attr("slot", value)
}

// Autocorrect 
// Element(s): HTML elements.
// Description: Recommended autocorrection behavior (for supported input methods).
// Value: "on"; "off".
func Autocorrect(value string) *AttributeStruct {
	return Attr("autocorrect", value)
}

// Dirname 
// Element(s): input; textarea.
// Description: Name of form control to use for sending the element's directionality in form submission.
// Value: Text*.
func Dirname(value string) *AttributeStruct {
	return Attr("dirname", value)
}

// Shadowrootserializable 
// Element(s): template.
// Description: Sets serializable on a declarative shadow root.
// Value: Boolean attribute.
func Shadowrootserializable(value bool) *AttributeStruct {
	return BooleanAttr("shadowrootserializable", value)
}

// Title 
// Element(s): HTML elements.
// Description: Advisory information for the element.
// Value: Text.
//
// Element(s): abbr; dfn.
// Description: Full term or expansion of abbreviation.
// Value: Text.
//
// Element(s): input.
// Description: Description of pattern (when used with pattern attribute).
// Value: Text.
//
// Element(s): link.
// Description: Title of the link.
// Value: Text.
//
// Element(s): link; style.
// Description: CSS style sheet set name.
// Value: Text.
func Title(value string) *AttributeStruct {
	return Attr("title", value)
}

// Loop 
// Element(s): audio; video.
// Description: Whether to loop the media resource.
// Value: Boolean attribute.
func Loop(value bool) *AttributeStruct {
	return BooleanAttr("loop", value)
}

// Popover 
// Element(s): HTML elements.
// Description: Makes the element a popover element.
// Value: "auto"; "manual";.
func Popover(value string) *AttributeStruct {
	return Attr("popover", value)
}

// AcceptCharset 
// Element(s): form.
// Description: Character encodings to use for form submission.
// Value: ASCII case-insensitive match for "UTF-8".
func AcceptCharset(value string) *AttributeStruct {
	return Attr("accept-charset", value)
}

// Accesskey 
// Element(s): HTML elements.
// Description: Keyboard shortcut to activate or focus element.
// Value: Ordered set of unique space-separated tokens, none of which are identical to another, each consisting of one code point in length.
func Accesskey(value string) *AttributeStruct {
	return Attr("accesskey", value)
}

// Coords 
// Element(s): area.
// Description: Coordinates for the shape to be created in an image map.
// Value: Valid list of floating-point numbers*.
func Coords(value string) *AttributeStruct {
	return Attr("coords", value)
}

// Default 
// Element(s): track.
// Description: Enable the track if no other text track is more suitable.
// Value: Boolean attribute.
func Default(value bool) *AttributeStruct {
	return BooleanAttr("default", value)
}

// Formtarget 
// Element(s): button; input.
// Description: Navigable for form submission.
// Value: Valid navigable target name or keyword.
func Formtarget(value string) *AttributeStruct {
	return Attr("formtarget", value)
}

// Datetime 
// Element(s): del; ins.
// Description: Date and (optionally) time of the change.
// Value: Valid date string with optional time.
//
// Element(s): time.
// Description: Machine-readable value.
// Value: Valid month string, valid date string, valid yearless date string, valid time string, valid local date and time string, valid time-zone offset string, valid global date and time string, valid week string, valid non-negative integer, or valid duration string.
func Datetime(value string) *AttributeStruct {
	return Attr("datetime", value)
}

// Inputmode 
// Element(s): HTML elements.
// Description: Hint for selecting an input modality.
// Value: "none"; "text"; "tel"; "email"; "url"; "numeric"; "decimal"; "search".
func Inputmode(value string) *AttributeStruct {
	return Attr("inputmode", value)
}

// List 
// Element(s): input.
// Description: List of autocomplete options.
// Value: ID*.
func List(value string) *AttributeStruct {
	return Attr("list", value)
}

// Name 
// Element(s): button; fieldset; input; output; select; textarea; form-associated custom elements.
// Description: Name of the element to use for form submission and in the form.elements API.
// Value: Text*.
//
// Element(s): details.
// Description: Name of group of mutually-exclusive details elements.
// Value: Text*.
//
// Element(s): form.
// Description: Name of form to use in the document.forms API.
// Value: Text*.
//
// Element(s): iframe; object.
// Description: Name of content navigable.
// Value: Valid navigable target name or keyword.
//
// Element(s): map.
// Description: Name of image map to reference from the usemap attribute.
// Value: Text*.
//
// Element(s): meta.
// Description: Metadata name.
// Value: Text*.
//
// Element(s): slot.
// Description: Name of shadow tree slot.
// Value: Text.
func Name(value string) *AttributeStruct {
	return Attr("name", value)
}

// Shadowrootdelegatesfocus 
// Element(s): template.
// Description: Sets delegates focus on a declarative shadow root.
// Value: Boolean attribute.
func Shadowrootdelegatesfocus(value bool) *AttributeStruct {
	return BooleanAttr("shadowrootdelegatesfocus", value)
}

// Allowfullscreen 
// Element(s): iframe.
// Description: Whether to allow the iframe's contents to use requestFullscreen().
// Value: Boolean attribute.
func Allowfullscreen(value bool) *AttributeStruct {
	return BooleanAttr("allowfullscreen", value)
}

// Alt 
// Element(s): area; img; input.
// Description: Replacement text for use when images are not available.
// Value: Text*.
func Alt(value string) *AttributeStruct {
	return Attr("alt", value)
}

// Autofocus 
// Element(s): HTML elements.
// Description: Automatically focus the element when the page is loaded.
// Value: Boolean attribute.
func Autofocus(value bool) *AttributeStruct {
	return BooleanAttr("autofocus", value)
}

// Srcdoc 
// Element(s): iframe.
// Description: A document to render in the iframe.
// Value: The source of an iframe srcdoc document*.
func Srcdoc(value string) *AttributeStruct {
	return Attr("srcdoc", value)
}

// Value 
// Element(s): button; option.
// Description: Value to be used for form submission.
// Value: Text.
//
// Element(s): data.
// Description: Machine-readable value.
// Value: Text*.
//
// Element(s): input.
// Description: Value of the form control.
// Value: Varies*.
//
// Element(s): li.
// Description: Ordinal value of the list item.
// Value: Valid integer.
//
// Element(s): meter; progress.
// Description: Current value of the element.
// Value: Valid floating-point number.
func Value(value string) *AttributeStruct {
	return Attr("value", value)
}

// Checked 
// Element(s): input.
// Description: Whether the control is checked.
// Value: Boolean attribute.
func Checked(value bool) *AttributeStruct {
	return BooleanAttr("checked", value)
}

// Dir 
// Element(s): HTML elements.
// Description: The text directionality of the element.
// Value: "ltr"; "rtl"; "auto".
//
// Element(s): bdo.
// Description: The text directionality of the element.
// Value: "ltr"; "rtl".
func Dir(value string) *AttributeStruct {
	return Attr("dir", value)
}

// For 
// Element(s): label.
// Description: Associate the label with form control.
// Value: ID*.
//
// Element(s): output.
// Description: Specifies controls from which the output was calculated.
// Value: Unordered set of unique space-separated tokens consisting of IDs*.
func For(value string) *AttributeStruct {
	return Attr("for", value)
}

// Rel 
// Element(s): a; area.
// Description: Relationship between the location in the document containing the hyperlink and the destination resource.
// Value: Unordered set of unique space-separated tokens*.
//
// Element(s): link.
// Description: Relationship between the document containing the hyperlink and the destination resource.
// Value: Unordered set of unique space-separated tokens*.
func Rel(value string) *AttributeStruct {
	return Attr("rel", value)
}

// Shape 
// Element(s): area.
// Description: The kind of shape to be created in an image map.
// Value: "circle"; "default"; "poly"; "rect".
func Shape(value string) *AttributeStruct {
	return Attr("shape", value)
}

// Tabindex 
// Element(s): HTML elements.
// Description: Whether the element is focusable and sequentially focusable, and the relative order of the element for the purposes of sequential focus navigation.
// Value: Valid integer.
func Tabindex(value string) *AttributeStruct {
	return Attr("tabindex", value)
}

// Start 
// Element(s): ol.
// Description: Starting value of the list.
// Value: Valid integer.
func Start(value string) *AttributeStruct {
	return Attr("start", value)
}

// Fetchpriority 
// Element(s): img; link; script.
// Description: Sets the priority for fetches initiated by the element.
// Value: "auto"; "high"; "low".
func Fetchpriority(value string) *AttributeStruct {
	return Attr("fetchpriority", value)
}

// Max 
// Element(s): input.
// Description: Maximum value.
// Value: Varies*.
//
// Element(s): meter; progress.
// Description: Upper bound of range.
// Value: Valid floating-point number*.
func Max(value string) *AttributeStruct {
	return Attr("max", value)
}

// Open 
// Element(s): details.
// Description: Whether the details are visible.
// Value: Boolean attribute.
//
// Element(s): dialog.
// Description: Whether the dialog box is showing.
// Value: Boolean attribute.
func Open(value bool) *AttributeStruct {
	return BooleanAttr("open", value)
}

// Readonly 
// Element(s): input; textarea.
// Description: Whether to allow the value to be edited by the user.
// Value: Boolean attribute.
//
// Element(s): form-associated custom elements.
// Description: Affects willValidate, plus any behavior added by the custom element author.
// Value: Boolean attribute.
func Readonly(value bool) *AttributeStruct {
	return BooleanAttr("readonly", value)
}

// Required 
// Element(s): input; select; textarea.
// Description: Whether the control is required for form submission.
// Value: Boolean attribute.
func Required(value bool) *AttributeStruct {
	return BooleanAttr("required", value)
}

// Nomodule 
// Element(s): script.
// Description: Prevents execution in user agents that support module scripts.
// Value: Boolean attribute.
func Nomodule(value bool) *AttributeStruct {
	return BooleanAttr("nomodule", value)
}

// Color 
// Element(s): link.
// Description: Color to use when customizing a site's icon (for rel="mask-icon").
// Value: CSS <color>.
func Color(value string) *AttributeStruct {
	return Attr("color", value)
}

// Decoding 
// Element(s): img.
// Description: Decoding hint to use when processing this image for presentation.
// Value: "sync"; "async"; "auto".
func Decoding(value string) *AttributeStruct {
	return Attr("decoding", value)
}

// Download 
// Element(s): a; area.
// Description: Whether to download the resource instead of navigating to it, and its filename if so.
// Value: Text.
func Download(value string) *AttributeStruct {
	return Attr("download", value)
}

// Formmethod 
// Element(s): button; input.
// Description: Variant to use for form submission.
// Value: "GET"; "POST"; "dialog".
func Formmethod(value string) *AttributeStruct {
	return Attr("formmethod", value)
}

// Itemscope 
// Element(s): HTML elements.
// Description: Introduces a microdata item.
// Value: Boolean attribute.
func Itemscope(value bool) *AttributeStruct {
	return BooleanAttr("itemscope", value)
}

// Usemap 
// Element(s): img.
// Description: Name of image map to use.
// Value: Valid hash-name reference*.
func Usemap(value string) *AttributeStruct {
	return Attr("usemap", value)
}

// Charset 
// Element(s): meta.
// Description: Character encoding declaration.
// Value: "utf-8".
func Charset(value string) *AttributeStruct {
	return Attr("charset", value)
}

// Colspan 
// Element(s): td; th.
// Description: Number of columns that the cell is to span.
// Value: Valid non-negative integer greater than zero.
func Colspan(value string) *AttributeStruct {
	return Attr("colspan", value)
}

// Enctype 
// Element(s): form.
// Description: Entry list encoding type to use for form submission.
// Value: "application/x-www-form-urlencoded"; "multipart/form-data"; "text/plain".
func Enctype(value string) *AttributeStruct {
	return Attr("enctype", value)
}

// Lang 
// Element(s): HTML elements.
// Description: Language of the element.
// Value: Valid BCP 47 language tag or the empty string.
func Lang(value string) *AttributeStruct {
	return Attr("lang", value)
}

// Maxlength 
// Element(s): input; textarea.
// Description: Maximum length of value.
// Value: Valid non-negative integer.
func Maxlength(value string) *AttributeStruct {
	return Attr("maxlength", value)
}

// Selected 
// Element(s): option.
// Description: Whether the option is selected by default.
// Value: Boolean attribute.
func Selected(value bool) *AttributeStruct {
	return BooleanAttr("selected", value)
}

// Shadowrootclonable 
// Element(s): template.
// Description: Sets clonable on a declarative shadow root.
// Value: Boolean attribute.
func Shadowrootclonable(value bool) *AttributeStruct {
	return BooleanAttr("shadowrootclonable", value)
}

// Formenctype 
// Element(s): button; input.
// Description: Entry list encoding type to use for form submission.
// Value: "application/x-www-form-urlencoded"; "multipart/form-data"; "text/plain".
func Formenctype(value string) *AttributeStruct {
	return Attr("formenctype", value)
}

// Imagesizes 
// Element(s): link.
// Description: Image sizes for different page layouts (for rel="preload").
// Value: Valid source size list.
func Imagesizes(value string) *AttributeStruct {
	return Attr("imagesizes", value)
}

// Ismap 
// Element(s): img.
// Description: Whether the image is a server-side image map.
// Value: Boolean attribute.
func Ismap(value bool) *AttributeStruct {
	return BooleanAttr("ismap", value)
}

// Min 
// Element(s): input.
// Description: Minimum value.
// Value: Varies*.
//
// Element(s): meter.
// Description: Lower bound of range.
// Value: Valid floating-point number*.
func Min(value string) *AttributeStruct {
	return Attr("min", value)
}

// Playsinline 
// Element(s): video.
// Description: Encourage the user agent to display video content within the element's playback area.
// Value: Boolean attribute.
func Playsinline(value bool) *AttributeStruct {
	return BooleanAttr("playsinline", value)
}

// Imagesrcset 
// Element(s): link.
// Description: Images to use in different situations, e.g., high-resolution displays, small monitors, etc. (for rel="preload").
// Value: Comma-separated list of image candidate strings.
func Imagesrcset(value string) *AttributeStruct {
	return Attr("imagesrcset", value)
}

// Referrerpolicy 
// Element(s): a; area; iframe; img; link; script.
// Description: Referrer policy for fetches initiated by the element.
// Value: Referrer policy.
func Referrerpolicy(value string) *AttributeStruct {
	return Attr("referrerpolicy", value)
}

// Blocking 
// Element(s): link; script; style.
// Description: Whether the element is potentially render-blocking.
// Value: Unordered set of unique space-separated tokens*.
func Blocking(value string) *AttributeStruct {
	return Attr("blocking", value)
}

// Label 
// Element(s): optgroup; option; track.
// Description: User-visible label.
// Value: Text.
func Label(value string) *AttributeStruct {
	return Attr("label", value)
}

// Span 
// Element(s): col; colgroup.
// Description: Number of columns spanned by the element.
// Value: Valid non-negative integer greater than zero.
func Span(value string) *AttributeStruct {
	return Attr("span", value)
}

// Srclang 
// Element(s): track.
// Description: Language of the text track.
// Value: Valid BCP 47 language tag.
func Srclang(value string) *AttributeStruct {
	return Attr("srclang", value)
}

// Crossorigin 
// Element(s): audio; img; link; script; video.
// Description: How the element handles crossorigin requests.
// Value: "anonymous"; "use-credentials".
func Crossorigin(value string) *AttributeStruct {
	return Attr("crossorigin", value)
}

// Disabled 
// Element(s): button; input; optgroup; option; select; textarea; form-associated custom elements.
// Description: Whether the form control is disabled.
// Value: Boolean attribute.
//
// Element(s): fieldset.
// Description: Whether the descendant form controls, except any inside legend, are disabled.
// Value: Boolean attribute.
//
// Element(s): link.
// Description: Whether the link is disabled.
// Value: Boolean attribute.
func Disabled(value bool) *AttributeStruct {
	return BooleanAttr("disabled", value)
}

// Kind 
// Element(s): track.
// Description: The type of text track.
// Value: "subtitles"; "captions"; "descriptions"; "chapters"; "metadata".
func Kind(value string) *AttributeStruct {
	return Attr("kind", value)
}

// Translate 
// Element(s): HTML elements.
// Description: Whether the element is to be translated when the page is localized.
// Value: "yes"; "no".
func Translate(value string) *AttributeStruct {
	return Attr("translate", value)
}

// Wrap 
// Element(s): textarea.
// Description: How the value of the form control is to be wrapped for form submission.
// Value: "soft"; "hard".
func Wrap(value string) *AttributeStruct {
	return Attr("wrap", value)
}


// Event Handler Attributes

// Onended 
// Element(s): HTML elements.
// Description: ended event handler.
// Value: Event handler content attribute.
func Onended(value string) *AttributeStruct {
	return RawAttr("onended", value)
}

// Onformdata 
// Element(s): HTML elements.
// Description: formdata event handler.
// Value: Event handler content attribute.
func Onformdata(value string) *AttributeStruct {
	return RawAttr("onformdata", value)
}

// Oninvalid 
// Element(s): HTML elements.
// Description: invalid event handler.
// Value: Event handler content attribute.
func Oninvalid(value string) *AttributeStruct {
	return RawAttr("oninvalid", value)
}

// Onmessageerror 
// Element(s): body.
// Description: messageerror event handler for Window object.
// Value: Event handler content attribute.
func Onmessageerror(value string) *AttributeStruct {
	return RawAttr("onmessageerror", value)
}

// Onoffline 
// Element(s): body.
// Description: offline event handler for Window object.
// Value: Event handler content attribute.
func Onoffline(value string) *AttributeStruct {
	return RawAttr("onoffline", value)
}

// Onpause 
// Element(s): HTML elements.
// Description: pause event handler.
// Value: Event handler content attribute.
func Onpause(value string) *AttributeStruct {
	return RawAttr("onpause", value)
}

// Onplaying 
// Element(s): HTML elements.
// Description: playing event handler.
// Value: Event handler content attribute.
func Onplaying(value string) *AttributeStruct {
	return RawAttr("onplaying", value)
}

// Onwaiting 
// Element(s): HTML elements.
// Description: waiting event handler.
// Value: Event handler content attribute.
func Onwaiting(value string) *AttributeStruct {
	return RawAttr("onwaiting", value)
}

// Onbeforeunload 
// Element(s): body.
// Description: beforeunload event handler for Window object.
// Value: Event handler content attribute.
func Onbeforeunload(value string) *AttributeStruct {
	return RawAttr("onbeforeunload", value)
}

// Oncanplaythrough 
// Element(s): HTML elements.
// Description: canplaythrough event handler.
// Value: Event handler content attribute.
func Oncanplaythrough(value string) *AttributeStruct {
	return RawAttr("oncanplaythrough", value)
}

// Onresize 
// Element(s): HTML elements.
// Description: resize event handler.
// Value: Event handler content attribute.
func Onresize(value string) *AttributeStruct {
	return RawAttr("onresize", value)
}

// Onsecuritypolicyviolation 
// Element(s): HTML elements.
// Description: securitypolicyviolation event handler.
// Value: Event handler content attribute.
func Onsecuritypolicyviolation(value string) *AttributeStruct {
	return RawAttr("onsecuritypolicyviolation", value)
}

// Onstorage 
// Element(s): body.
// Description: storage event handler for Window object.
// Value: Event handler content attribute.
func Onstorage(value string) *AttributeStruct {
	return RawAttr("onstorage", value)
}

// Onbeforematch 
// Element(s): HTML elements.
// Description: beforematch event handler.
// Value: Event handler content attribute.
func Onbeforematch(value string) *AttributeStruct {
	return RawAttr("onbeforematch", value)
}

// Oncanplay 
// Element(s): HTML elements.
// Description: canplay event handler.
// Value: Event handler content attribute.
func Oncanplay(value string) *AttributeStruct {
	return RawAttr("oncanplay", value)
}

// Onchange 
// Element(s): HTML elements.
// Description: change event handler.
// Value: Event handler content attribute.
func Onchange(value string) *AttributeStruct {
	return RawAttr("onchange", value)
}

// Oncontextmenu 
// Element(s): HTML elements.
// Description: contextmenu event handler.
// Value: Event handler content attribute.
func Oncontextmenu(value string) *AttributeStruct {
	return RawAttr("oncontextmenu", value)
}

// Ondrop 
// Element(s): HTML elements.
// Description: drop event handler.
// Value: Event handler content attribute.
func Ondrop(value string) *AttributeStruct {
	return RawAttr("ondrop", value)
}

// Oninput 
// Element(s): HTML elements.
// Description: input event handler.
// Value: Event handler content attribute.
func Oninput(value string) *AttributeStruct {
	return RawAttr("oninput", value)
}

// Onmouseover 
// Element(s): HTML elements.
// Description: mouseover event handler.
// Value: Event handler content attribute.
func Onmouseover(value string) *AttributeStruct {
	return RawAttr("onmouseover", value)
}

// Onscroll 
// Element(s): HTML elements.
// Description: scroll event handler.
// Value: Event handler content attribute.
func Onscroll(value string) *AttributeStruct {
	return RawAttr("onscroll", value)
}

// Onunload 
// Element(s): body.
// Description: unload event handler for Window object.
// Value: Event handler content attribute.
func Onunload(value string) *AttributeStruct {
	return RawAttr("onunload", value)
}

// Onbeforeprint 
// Element(s): body.
// Description: beforeprint event handler for Window object.
// Value: Event handler content attribute.
func Onbeforeprint(value string) *AttributeStruct {
	return RawAttr("onbeforeprint", value)
}

// Onmousemove 
// Element(s): HTML elements.
// Description: mousemove event handler.
// Value: Event handler content attribute.
func Onmousemove(value string) *AttributeStruct {
	return RawAttr("onmousemove", value)
}

// Onselect 
// Element(s): HTML elements.
// Description: select event handler.
// Value: Event handler content attribute.
func Onselect(value string) *AttributeStruct {
	return RawAttr("onselect", value)
}

// Onslotchange 
// Element(s): HTML elements.
// Description: slotchange event handler.
// Value: Event handler content attribute.
func Onslotchange(value string) *AttributeStruct {
	return RawAttr("onslotchange", value)
}

// Onvolumechange 
// Element(s): HTML elements.
// Description: volumechange event handler.
// Value: Event handler content attribute.
func Onvolumechange(value string) *AttributeStruct {
	return RawAttr("onvolumechange", value)
}

// Onmouseleave 
// Element(s): HTML elements.
// Description: mouseleave event handler.
// Value: Event handler content attribute.
func Onmouseleave(value string) *AttributeStruct {
	return RawAttr("onmouseleave", value)
}

// Ononline 
// Element(s): body.
// Description: online event handler for Window object.
// Value: Event handler content attribute.
func Ononline(value string) *AttributeStruct {
	return RawAttr("ononline", value)
}

// Onpageshow 
// Element(s): body.
// Description: pageshow event handler for Window object.
// Value: Event handler content attribute.
func Onpageshow(value string) *AttributeStruct {
	return RawAttr("onpageshow", value)
}

// Onplay 
// Element(s): HTML elements.
// Description: play event handler.
// Value: Event handler content attribute.
func Onplay(value string) *AttributeStruct {
	return RawAttr("onplay", value)
}

// Onauxclick 
// Element(s): HTML elements.
// Description: auxclick event handler.
// Value: Event handler content attribute.
func Onauxclick(value string) *AttributeStruct {
	return RawAttr("onauxclick", value)
}

// Onmouseenter 
// Element(s): HTML elements.
// Description: mouseenter event handler.
// Value: Event handler content attribute.
func Onmouseenter(value string) *AttributeStruct {
	return RawAttr("onmouseenter", value)
}

// Onbeforetoggle 
// Element(s): HTML elements.
// Description: beforetoggle event handler.
// Value: Event handler content attribute.
func Onbeforetoggle(value string) *AttributeStruct {
	return RawAttr("onbeforetoggle", value)
}

// Onloadeddata 
// Element(s): HTML elements.
// Description: loadeddata event handler.
// Value: Event handler content attribute.
func Onloadeddata(value string) *AttributeStruct {
	return RawAttr("onloadeddata", value)
}

// Onloadedmetadata 
// Element(s): HTML elements.
// Description: loadedmetadata event handler.
// Value: Event handler content attribute.
func Onloadedmetadata(value string) *AttributeStruct {
	return RawAttr("onloadedmetadata", value)
}

// Onloadstart 
// Element(s): HTML elements.
// Description: loadstart event handler.
// Value: Event handler content attribute.
func Onloadstart(value string) *AttributeStruct {
	return RawAttr("onloadstart", value)
}

// Onpagehide 
// Element(s): body.
// Description: pagehide event handler for Window object.
// Value: Event handler content attribute.
func Onpagehide(value string) *AttributeStruct {
	return RawAttr("onpagehide", value)
}

// Onscrollend 
// Element(s): HTML elements.
// Description: scrollend event handler.
// Value: Event handler content attribute.
func Onscrollend(value string) *AttributeStruct {
	return RawAttr("onscrollend", value)
}

// Ondblclick 
// Element(s): HTML elements.
// Description: dblclick event handler.
// Value: Event handler content attribute.
func Ondblclick(value string) *AttributeStruct {
	return RawAttr("ondblclick", value)
}

// Ondurationchange 
// Element(s): HTML elements.
// Description: durationchange event handler.
// Value: Event handler content attribute.
func Ondurationchange(value string) *AttributeStruct {
	return RawAttr("ondurationchange", value)
}

// Onemptied 
// Element(s): HTML elements.
// Description: emptied event handler.
// Value: Event handler content attribute.
func Onemptied(value string) *AttributeStruct {
	return RawAttr("onemptied", value)
}

// Onsuspend 
// Element(s): HTML elements.
// Description: suspend event handler.
// Value: Event handler content attribute.
func Onsuspend(value string) *AttributeStruct {
	return RawAttr("onsuspend", value)
}

// Onclose 
// Element(s): HTML elements.
// Description: close event handler.
// Value: Event handler content attribute.
func Onclose(value string) *AttributeStruct {
	return RawAttr("onclose", value)
}

// Oncontextrestored 
// Element(s): HTML elements.
// Description: contextrestored event handler.
// Value: Event handler content attribute.
func Oncontextrestored(value string) *AttributeStruct {
	return RawAttr("oncontextrestored", value)
}

// Oncopy 
// Element(s): HTML elements.
// Description: copy event handler.
// Value: Event handler content attribute.
func Oncopy(value string) *AttributeStruct {
	return RawAttr("oncopy", value)
}

// Onpageswap 
// Element(s): body.
// Description: pageswap event handler for Window object.
// Value: Event handler content attribute.
func Onpageswap(value string) *AttributeStruct {
	return RawAttr("onpageswap", value)
}

// Onpaste 
// Element(s): HTML elements.
// Description: paste event handler.
// Value: Event handler content attribute.
func Onpaste(value string) *AttributeStruct {
	return RawAttr("onpaste", value)
}

// Onseeking 
// Element(s): HTML elements.
// Description: seeking event handler.
// Value: Event handler content attribute.
func Onseeking(value string) *AttributeStruct {
	return RawAttr("onseeking", value)
}

// Onstalled 
// Element(s): HTML elements.
// Description: stalled event handler.
// Value: Event handler content attribute.
func Onstalled(value string) *AttributeStruct {
	return RawAttr("onstalled", value)
}

// Onsubmit 
// Element(s): HTML elements.
// Description: submit event handler.
// Value: Event handler content attribute.
func Onsubmit(value string) *AttributeStruct {
	return RawAttr("onsubmit", value)
}

// Onunhandledrejection 
// Element(s): body.
// Description: unhandledrejection event handler for Window object.
// Value: Event handler content attribute.
func Onunhandledrejection(value string) *AttributeStruct {
	return RawAttr("onunhandledrejection", value)
}

// Onratechange 
// Element(s): HTML elements.
// Description: ratechange event handler.
// Value: Event handler content attribute.
func Onratechange(value string) *AttributeStruct {
	return RawAttr("onratechange", value)
}

// Onblur 
// Element(s): HTML elements.
// Description: blur event handler.
// Value: Event handler content attribute.
func Onblur(value string) *AttributeStruct {
	return RawAttr("onblur", value)
}

// Oncancel 
// Element(s): HTML elements.
// Description: cancel event handler.
// Value: Event handler content attribute.
func Oncancel(value string) *AttributeStruct {
	return RawAttr("oncancel", value)
}

// Ondragstart 
// Element(s): HTML elements.
// Description: dragstart event handler.
// Value: Event handler content attribute.
func Ondragstart(value string) *AttributeStruct {
	return RawAttr("ondragstart", value)
}

// Onkeyup 
// Element(s): HTML elements.
// Description: keyup event handler.
// Value: Event handler content attribute.
func Onkeyup(value string) *AttributeStruct {
	return RawAttr("onkeyup", value)
}

// Onrejectionhandled 
// Element(s): body.
// Description: rejectionhandled event handler for Window object.
// Value: Event handler content attribute.
func Onrejectionhandled(value string) *AttributeStruct {
	return RawAttr("onrejectionhandled", value)
}

// Oncuechange 
// Element(s): HTML elements.
// Description: cuechange event handler.
// Value: Event handler content attribute.
func Oncuechange(value string) *AttributeStruct {
	return RawAttr("oncuechange", value)
}

// Ondrag 
// Element(s): HTML elements.
// Description: drag event handler.
// Value: Event handler content attribute.
func Ondrag(value string) *AttributeStruct {
	return RawAttr("ondrag", value)
}

// Ondragenter 
// Element(s): HTML elements.
// Description: dragenter event handler.
// Value: Event handler content attribute.
func Ondragenter(value string) *AttributeStruct {
	return RawAttr("ondragenter", value)
}

// Onfocus 
// Element(s): HTML elements.
// Description: focus event handler.
// Value: Event handler content attribute.
func Onfocus(value string) *AttributeStruct {
	return RawAttr("onfocus", value)
}

// Onlanguagechange 
// Element(s): body.
// Description: languagechange event handler for Window object.
// Value: Event handler content attribute.
func Onlanguagechange(value string) *AttributeStruct {
	return RawAttr("onlanguagechange", value)
}

// Onmouseup 
// Element(s): HTML elements.
// Description: mouseup event handler.
// Value: Event handler content attribute.
func Onmouseup(value string) *AttributeStruct {
	return RawAttr("onmouseup", value)
}

// Ontimeupdate 
// Element(s): HTML elements.
// Description: timeupdate event handler.
// Value: Event handler content attribute.
func Ontimeupdate(value string) *AttributeStruct {
	return RawAttr("ontimeupdate", value)
}

// Onbeforeinput 
// Element(s): HTML elements.
// Description: beforeinput event handler.
// Value: Event handler content attribute.
func Onbeforeinput(value string) *AttributeStruct {
	return RawAttr("onbeforeinput", value)
}

// Onclick 
// Element(s): HTML elements.
// Description: click event handler.
// Value: Event handler content attribute.
func Onclick(value string) *AttributeStruct {
	return RawAttr("onclick", value)
}

// Onmessage 
// Element(s): body.
// Description: message event handler for Window object.
// Value: Event handler content attribute.
func Onmessage(value string) *AttributeStruct {
	return RawAttr("onmessage", value)
}

// Onpopstate 
// Element(s): body.
// Description: popstate event handler for Window object.
// Value: Event handler content attribute.
func Onpopstate(value string) *AttributeStruct {
	return RawAttr("onpopstate", value)
}

// Onseeked 
// Element(s): HTML elements.
// Description: seeked event handler.
// Value: Event handler content attribute.
func Onseeked(value string) *AttributeStruct {
	return RawAttr("onseeked", value)
}

// Oncontextlost 
// Element(s): HTML elements.
// Description: contextlost event handler.
// Value: Event handler content attribute.
func Oncontextlost(value string) *AttributeStruct {
	return RawAttr("oncontextlost", value)
}

// Oncut 
// Element(s): HTML elements.
// Description: cut event handler.
// Value: Event handler content attribute.
func Oncut(value string) *AttributeStruct {
	return RawAttr("oncut", value)
}

// Ondragleave 
// Element(s): HTML elements.
// Description: dragleave event handler.
// Value: Event handler content attribute.
func Ondragleave(value string) *AttributeStruct {
	return RawAttr("ondragleave", value)
}

// Ondragover 
// Element(s): HTML elements.
// Description: dragover event handler.
// Value: Event handler content attribute.
func Ondragover(value string) *AttributeStruct {
	return RawAttr("ondragover", value)
}

// Onerror 
// Element(s): HTML elements.
// Description: error event handler.
// Value: Event handler content attribute.
func Onerror(value string) *AttributeStruct {
	return RawAttr("onerror", value)
}

// Onkeydown 
// Element(s): HTML elements.
// Description: keydown event handler.
// Value: Event handler content attribute.
func Onkeydown(value string) *AttributeStruct {
	return RawAttr("onkeydown", value)
}

// Onmousedown 
// Element(s): HTML elements.
// Description: mousedown event handler.
// Value: Event handler content attribute.
func Onmousedown(value string) *AttributeStruct {
	return RawAttr("onmousedown", value)
}

// Onmouseout 
// Element(s): HTML elements.
// Description: mouseout event handler.
// Value: Event handler content attribute.
func Onmouseout(value string) *AttributeStruct {
	return RawAttr("onmouseout", value)
}

// Ontoggle 
// Element(s): HTML elements.
// Description: toggle event handler.
// Value: Event handler content attribute.
func Ontoggle(value string) *AttributeStruct {
	return RawAttr("ontoggle", value)
}

// Onafterprint 
// Element(s): body.
// Description: afterprint event handler for Window object.
// Value: Event handler content attribute.
func Onafterprint(value string) *AttributeStruct {
	return RawAttr("onafterprint", value)
}

// Onpagereveal 
// Element(s): body.
// Description: pagereveal event handler for Window object.
// Value: Event handler content attribute.
func Onpagereveal(value string) *AttributeStruct {
	return RawAttr("onpagereveal", value)
}

// Onreset 
// Element(s): HTML elements.
// Description: reset event handler.
// Value: Event handler content attribute.
func Onreset(value string) *AttributeStruct {
	return RawAttr("onreset", value)
}

// Onwheel 
// Element(s): HTML elements.
// Description: wheel event handler.
// Value: Event handler content attribute.
func Onwheel(value string) *AttributeStruct {
	return RawAttr("onwheel", value)
}

// Oncommand 
// Element(s): HTML elements.
// Description: command event handler.
// Value: Event handler content attribute.
func Oncommand(value string) *AttributeStruct {
	return RawAttr("oncommand", value)
}

// Ondragend 
// Element(s): HTML elements.
// Description: dragend event handler.
// Value: Event handler content attribute.
func Ondragend(value string) *AttributeStruct {
	return RawAttr("ondragend", value)
}

// Onhashchange 
// Element(s): body.
// Description: hashchange event handler for Window object.
// Value: Event handler content attribute.
func Onhashchange(value string) *AttributeStruct {
	return RawAttr("onhashchange", value)
}

// Onkeypress 
// Element(s): HTML elements.
// Description: keypress event handler.
// Value: Event handler content attribute.
func Onkeypress(value string) *AttributeStruct {
	return RawAttr("onkeypress", value)
}

// Onload 
// Element(s): HTML elements.
// Description: load event handler.
// Value: Event handler content attribute.
func Onload(value string) *AttributeStruct {
	return RawAttr("onload", value)
}

// Onprogress 
// Element(s): HTML elements.
// Description: progress event handler.
// Value: Event handler content attribute.
func Onprogress(value string) *AttributeStruct {
	return RawAttr("onprogress", value)
}
