// Code generated by "go run -C ../../generate ./"; DO NOT EDIT.
// HTML spec at https://html.spec.whatwg.org/multipage/indices.html

package elems

import "github.com/ramonpetgrave64/go-html-compose/pkg/doc"

// Special Elements

// Doctype is a required preamble.
var Doctype = doc.ChildElem("!DOCTYPE html")

// Regular Elements

// A
// Description: Hyperlink.
// Categories: flow; phrasing*; interactive; palpable.
// Parents: phrasing.
// Children: transparent*.
// Attributes: globals; href; target; download; ping; rel; hreflang; type; referrerpolicy
func A(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("a", attrs...)
}

// Abbr
// Description: Abbreviation.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Abbr(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("abbr", attrs...)
}

// Address
// Description: Contact information for a page or article element.
// Categories: flow; palpable.
// Parents: flow.
// Children: flow*.
// Attributes: globals
func Address(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("address", attrs...)
}

// Area
// Description: Hyperlink or dead area on an image map.
// Categories: flow; phrasing.
// Parents: phrasing*.
// Children: empty.
// Attributes: globals; alt; coords; shape; href; target; download; ping; rel; referrerpolicy
func Area(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("area", attrs...)
}

// Article
// Description: Self-contained syndicatable or reusable composition.
// Categories: flow; sectioning; palpable.
// Parents: flow.
// Children: flow.
// Attributes: globals
func Article(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("article", attrs...)
}

// Aside
// Description: Sidebar for tangentially related content.
// Categories: flow; sectioning; palpable.
// Parents: flow.
// Children: flow.
// Attributes: globals
func Aside(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("aside", attrs...)
}

// Audio
// Description: Audio player.
// Categories: flow; phrasing; embedded; interactive; palpable*.
// Parents: phrasing.
// Children: source*; track*; transparent*.
// Attributes: globals; src; crossorigin; preload; autoplay; loop; muted; controls
func Audio(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("audio", attrs...)
}

// B
// Description: Keywords.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func B(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("b", attrs...)
}

// Base
// Description: Base URL and default target navigable for hyperlinks and forms.
// Categories: metadata.
// Parents: head.
// Children: empty.
// Attributes: globals; href; target
func Base(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("base", attrs...)
}

// Bdi
// Description: Text directionality isolation.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Bdi(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("bdi", attrs...)
}

// Bdo
// Description: Text directionality formatting.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Bdo(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("bdo", attrs...)
}

// Blockquote
// Description: A section quoted from another source.
// Categories: flow; palpable.
// Parents: flow.
// Children: flow.
// Attributes: globals; cite
func Blockquote(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("blockquote", attrs...)
}

// Body
// Description: Document body.
// Categories: none.
// Parents: html.
// Children: flow.
// Attributes: globals; onafterprint; onbeforeprint; onbeforeunload; onhashchange; onlanguagechange; onmessage; onmessageerror; onoffline; ononline; onpageswap; onpagehide; onpagereveal; onpageshow; onpopstate; onrejectionhandled; onstorage; onunhandledrejection; onunload
func Body(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("body", attrs...)
}

// Br
// Description: Line break, e.g. in poem or postal address.
// Categories: flow; phrasing.
// Parents: phrasing.
// Children: empty.
// Attributes: globals
func Br(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("br", attrs...)
}

// Button
// Description: Button control.
// Categories: flow; phrasing; interactive; listed; labelable; submittable; form-associated; palpable.
// Parents: phrasing.
// Children: phrasing*.
// Attributes: globals; command; commandfor; disabled; form; formaction; formenctype; formmethod; formnovalidate; formtarget; name; popovertarget; popovertargetaction; type; value
func Button(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("button", attrs...)
}

// Canvas
// Description: Scriptable bitmap canvas.
// Categories: flow; phrasing; embedded; palpable.
// Parents: phrasing.
// Children: transparent.
// Attributes: globals; width; height
func Canvas(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("canvas", attrs...)
}

// Caption
// Description: Table caption.
// Categories: none.
// Parents: table.
// Children: flow*.
// Attributes: globals
func Caption(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("caption", attrs...)
}

// Cite
// Description: Title of a work.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Cite(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("cite", attrs...)
}

// Code
// Description: Computer code.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Code(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("code", attrs...)
}

// Col
// Description: Table column.
// Categories: none.
// Parents: colgroup.
// Children: empty.
// Attributes: globals; span
func Col(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("col", attrs...)
}

// Colgroup
// Description: Group of columns in a table.
// Categories: none.
// Parents: table.
// Children: col*; template*.
// Attributes: globals; span
func Colgroup(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("colgroup", attrs...)
}

// Data
// Description: Machine-readable equivalent.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals; value
func Data(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("data", attrs...)
}

// Datalist
// Description: Container for options for combo box control.
// Categories: flow; phrasing.
// Parents: phrasing.
// Children: phrasing*; option*; script-supporting elements*.
// Attributes: globals
func Datalist(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("datalist", attrs...)
}

// Dd
// Description: Content for corresponding dt element(s).
// Categories: none.
// Parents: dl; div*.
// Children: flow.
// Attributes: globals
func Dd(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("dd", attrs...)
}

// Del
// Description: A removal from the document.
// Categories: flow; phrasing*; palpable.
// Parents: phrasing.
// Children: transparent.
// Attributes: globals; cite; datetime
func Del(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("del", attrs...)
}

// Details
// Description: Disclosure control for hiding details.
// Categories: flow; interactive; palpable.
// Parents: flow.
// Children: summary*; flow.
// Attributes: globals; name; open
func Details(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("details", attrs...)
}

// Dfn
// Description: Defining instance.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing*.
// Attributes: globals
func Dfn(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("dfn", attrs...)
}

// Dialog
// Description: Dialog box or window.
// Categories: flow.
// Parents: flow.
// Children: flow.
// Attributes: globals; open
func Dialog(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("dialog", attrs...)
}

// Div
// Description: Generic flow container, or container for name-value groups in dl elements.
// Categories: flow; palpable; select element inner content elements; optgroup element inner content elements; option element inner content elements.
// Parents: flow; dl; select element inner content elements; optgroup element inner content elements; option element inner content elements.
// Children: flow select element inner content elements*; optgroup element inner content elements*; option element inner content elements*.
// Attributes: globals
func Div(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("div", attrs...)
}

// Dl
// Description: Association list consisting of zero or more name-value groups.
// Categories: flow; palpable.
// Parents: flow.
// Children: dt*; dd*; div*; script-supporting elements.
// Attributes: globals
func Dl(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("dl", attrs...)
}

// Dt
// Description: Legend for corresponding dd element(s).
// Categories: none.
// Parents: dl; div*.
// Children: flow*.
// Attributes: globals
func Dt(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("dt", attrs...)
}

// Em
// Description: Stress emphasis.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Em(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("em", attrs...)
}

// Embed
// Description: Plugin.
// Categories: flow; phrasing; embedded; interactive; palpable.
// Parents: phrasing.
// Children: empty.
// Attributes: globals; src; type; width; height; any*
func Embed(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("embed", attrs...)
}

// Fieldset
// Description: Group of form controls.
// Categories: flow; listed; form-associated; palpable.
// Parents: flow.
// Children: legend*; flow.
// Attributes: globals; disabled; form; name
func Fieldset(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("fieldset", attrs...)
}

// Figcaption
// Description: Caption for figure.
// Categories: none.
// Parents: figure.
// Children: flow.
// Attributes: globals
func Figcaption(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("figcaption", attrs...)
}

// Figure
// Description: Figure with optional caption.
// Categories: flow; palpable.
// Parents: flow.
// Children: figcaption*; flow.
// Attributes: globals
func Figure(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("figure", attrs...)
}

// Footer
// Description: Footer for a page or section.
// Categories: flow; palpable.
// Parents: flow.
// Children: flow*.
// Attributes: globals
func Footer(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("footer", attrs...)
}

// Form
// Description: User-submittable form.
// Categories: flow; palpable.
// Parents: flow.
// Children: flow*.
// Attributes: globals; accept-charset; action; autocomplete; enctype; method; name; novalidate; rel; target
func Form(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("form", attrs...)
}

// H1
// Description: Heading.
// Categories: flow; heading; palpable.
// Parents: legend; summary; flow.
// Children: phrasing.
// Attributes: globals
func H1(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("h1", attrs...)
}

// H2
// Description: Heading.
// Categories: flow; heading; palpable.
// Parents: legend; summary; flow.
// Children: phrasing.
// Attributes: globals
func H2(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("h2", attrs...)
}

// H3
// Description: Heading.
// Categories: flow; heading; palpable.
// Parents: legend; summary; flow.
// Children: phrasing.
// Attributes: globals
func H3(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("h3", attrs...)
}

// H4
// Description: Heading.
// Categories: flow; heading; palpable.
// Parents: legend; summary; flow.
// Children: phrasing.
// Attributes: globals
func H4(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("h4", attrs...)
}

// H5
// Description: Heading.
// Categories: flow; heading; palpable.
// Parents: legend; summary; flow.
// Children: phrasing.
// Attributes: globals
func H5(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("h5", attrs...)
}

// H6
// Description: Heading.
// Categories: flow; heading; palpable.
// Parents: legend; summary; flow.
// Children: phrasing.
// Attributes: globals
func H6(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("h6", attrs...)
}

// Head
// Description: Container for document metadata.
// Categories: none.
// Parents: html.
// Children: metadata content*.
// Attributes: globals
func Head(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("head", attrs...)
}

// Header
// Description: Introductory or navigational aids for a page or section.
// Categories: flow; palpable.
// Parents: flow.
// Children: flow*.
// Attributes: globals
func Header(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("header", attrs...)
}

// Hgroup
// Description: Heading container.
// Categories: flow; palpable.
// Parents: legend; summary; flow.
// Children: h1; h2; h3; h4; h5; h6; p; script-supporting elements.
// Attributes: globals
func Hgroup(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("hgroup", attrs...)
}

// Hr
// Description: Thematic break.
// Categories: flow; select element inner content elements.
// Parents: flow; select element inner content elements.
// Children: empty.
// Attributes: globals
func Hr(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("hr", attrs...)
}

// Html
// Description: Root element.
// Categories: none.
// Parents: none*.
// Children: head*; body*.
// Attributes: globals
func Html(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("html", attrs...)
}

// I
// Description: Alternate voice.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func I(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("i", attrs...)
}

// Iframe
// Description: Child navigable.
// Categories: flow; phrasing; embedded; interactive; palpable.
// Parents: phrasing.
// Children: empty.
// Attributes: globals; src; srcdoc; name; sandbox; allow; allowfullscreen; width; height; referrerpolicy; loading
func Iframe(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("iframe", attrs...)
}

// Img
// Description: Image.
// Categories: flow; phrasing; embedded; interactive*; form-associated; palpable.
// Parents: phrasing; picture.
// Children: empty.
// Attributes: globals; alt; src; srcset; sizes; crossorigin; usemap; ismap; width; height; referrerpolicy; decoding; loading; fetchpriority
func Img(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("img", attrs...)
}

// Input
// Description: Form control.
// Categories: flow; phrasing; interactive*; listed; labelable; submittable; resettable; form-associated; palpable*.
// Parents: phrasing.
// Children: empty.
// Attributes: globals; accept; alpha; alt; autocomplete; checked; colorspace; dirname; disabled; form; formaction; formenctype; formmethod; formnovalidate; formtarget; height; list; max; maxlength; min; minlength; multiple; name; pattern; placeholder; popovertarget; popovertargetaction; readonly; required; size; src; step; type; value; width
func Input(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("input", attrs...)
}

// Ins
// Description: An addition to the document.
// Categories: flow; phrasing*; palpable.
// Parents: phrasing.
// Children: transparent.
// Attributes: globals; cite; datetime
func Ins(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("ins", attrs...)
}

// Kbd
// Description: User input.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Kbd(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("kbd", attrs...)
}

// Label
// Description: Caption for a form control.
// Categories: flow; phrasing; interactive; palpable.
// Parents: phrasing.
// Children: phrasing*.
// Attributes: globals; for
func Label(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("label", attrs...)
}

// Legend
// Description: Caption for fieldset.
// Categories: none.
// Parents: fieldset; optgroup.
// Children: phrasing*; heading content.
// Attributes: globals
func Legend(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("legend", attrs...)
}

// Li
// Description: List item.
// Categories: none.
// Parents: ol; ul; menu*.
// Children: flow.
// Attributes: globals; value*
func Li(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("li", attrs...)
}

// Link
// Description: Link metadata.
// Categories: metadata; flow*; phrasing*.
// Parents: head; noscript*; phrasing*.
// Children: empty.
// Attributes: globals; href; crossorigin; rel; as; media; hreflang; type; sizes; imagesrcset; imagesizes; referrerpolicy; integrity; blocking; color; disabled; fetchpriority
func Link(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("link", attrs...)
}

// Main
// Description: Container for the dominant contents of the document.
// Categories: flow; palpable.
// Parents: flow*.
// Children: flow.
// Attributes: globals
func Main(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("main", attrs...)
}

// Map
// Description: Image map.
// Categories: flow; phrasing*; palpable.
// Parents: phrasing.
// Children: transparent; area*.
// Attributes: globals; name
func Map(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("map", attrs...)
}

// Mark
// Description: Highlight.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Mark(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("mark", attrs...)
}

// Math
// Description: MathML root.
// Categories: flow; phrasing; embedded; palpable.
// Parents: phrasing.
// Children: per [MATHML].
// Attributes: per [MATHML]
func Math(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("math", attrs...)
}

// Menu
// Description: Menu of commands.
// Categories: flow; palpable*.
// Parents: flow.
// Children: li; script-supporting elements.
// Attributes: globals
func Menu(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("menu", attrs...)
}

// Meta
// Description: Text metadata.
// Categories: metadata; flow*; phrasing*.
// Parents: head; noscript*; phrasing*.
// Children: empty.
// Attributes: globals; name; http-equiv; content; charset; media
func Meta(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("meta", attrs...)
}

// Meter
// Description: Gauge.
// Categories: flow; phrasing; labelable; palpable.
// Parents: phrasing.
// Children: phrasing*.
// Attributes: globals; value; min; max; low; high; optimum
func Meter(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("meter", attrs...)
}

// Nav
// Description: Section with navigational links.
// Categories: flow; sectioning; palpable.
// Parents: flow.
// Children: flow.
// Attributes: globals
func Nav(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("nav", attrs...)
}

// Noscript
// Description: Fallback content for script.
// Categories: metadata; flow; phrasing; select element inner content elements; optgroup element inner content elements.
// Parents: head*; phrasing*.
// Children: varies*.
// Attributes: globals
func Noscript(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("noscript", attrs...)
}

// Object
// Description: Image, child navigable, or plugin.
// Categories: flow; phrasing; embedded; interactive*; listed; form-associated; palpable.
// Parents: phrasing.
// Children: transparent.
// Attributes: globals; data; type; name; form; width; height
func Object(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("object", attrs...)
}

// Ol
// Description: Ordered list.
// Categories: flow; palpable*.
// Parents: flow.
// Children: li; script-supporting elements.
// Attributes: globals; reversed; start; type
func Ol(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("ol", attrs...)
}

// Optgroup
// Description: Group of options in a list box.
// Categories: select element inner content elements.
// Parents: select; div*.
// Children: optgroup element inner content elements; legend*.
// Attributes: globals; disabled; label
func Optgroup(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("optgroup", attrs...)
}

// Option
// Description: Option in a list box or combo box control.
// Categories: select element inner content elements; optgroup element inner content elements.
// Parents: select; datalist; optgroup; div*.
// Children: text*; option element inner content elements*.
// Attributes: globals; disabled; label; selected; value
func Option(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("option", attrs...)
}

// Output
// Description: Calculated output value.
// Categories: flow; phrasing; listed; labelable; resettable; form-associated; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals; for; form; name
func Output(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("output", attrs...)
}

// P
// Description: Paragraph.
// Categories: flow; palpable.
// Parents: flow.
// Children: phrasing.
// Attributes: globals
func P(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("p", attrs...)
}

// Picture
// Description: Image.
// Categories: flow; phrasing; embedded; palpable.
// Parents: phrasing.
// Children: source*; one img; script-supporting elements.
// Attributes: globals
func Picture(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("picture", attrs...)
}

// Pre
// Description: Block of preformatted text.
// Categories: flow; palpable.
// Parents: flow.
// Children: phrasing.
// Attributes: globals
func Pre(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("pre", attrs...)
}

// Progress
// Description: Progress bar.
// Categories: flow; phrasing; labelable; palpable.
// Parents: phrasing.
// Children: phrasing*.
// Attributes: globals; value; max
func Progress(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("progress", attrs...)
}

// Q
// Description: Quotation.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals; cite
func Q(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("q", attrs...)
}

// Rp
// Description: Parenthesis for ruby annotation text.
// Categories: none.
// Parents: ruby.
// Children: text.
// Attributes: globals
func Rp(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("rp", attrs...)
}

// Rt
// Description: Ruby annotation text.
// Categories: none.
// Parents: ruby.
// Children: phrasing.
// Attributes: globals
func Rt(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("rt", attrs...)
}

// Ruby
// Description: Ruby annotation(s).
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing; rt; rp*.
// Attributes: globals
func Ruby(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("ruby", attrs...)
}

// S
// Description: Inaccurate text.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func S(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("s", attrs...)
}

// Samp
// Description: Computer output.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Samp(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("samp", attrs...)
}

// Script
// Description: Embedded script.
// Categories: metadata; flow; phrasing; script-supporting.
// Parents: head; phrasing; script-supporting.
// Children: script, data, or script documentation*.
// Attributes: globals; src; type; nomodule; async; defer; crossorigin; integrity; referrerpolicy; blocking; fetchpriority
func Script(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("script", attrs...)
}

// Search
// Description: Container for search controls.
// Categories: flow; palpable.
// Parents: flow.
// Children: flow.
// Attributes: globals
func Search(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("search", attrs...)
}

// Section
// Description: Generic document or application section.
// Categories: flow; sectioning; palpable.
// Parents: flow.
// Children: flow.
// Attributes: globals
func Section(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("section", attrs...)
}

// Select
// Description: List box control.
// Categories: flow; phrasing; interactive; listed; labelable; submittable; resettable; form-associated; palpable.
// Parents: phrasing.
// Children: select element inner content elements; button*.
// Attributes: globals; autocomplete; disabled; form; multiple; name; required; size
func Select(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("select", attrs...)
}

// Selectedcontent
// Description: Mirrors content from an option.
// Categories: none.
// Parents: button.
// Children: empty.
// Attributes: globals
func Selectedcontent(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("selectedcontent", attrs...)
}

// Slot
// Description: Shadow tree slot.
// Categories: flow; phrasing.
// Parents: phrasing.
// Children: transparent.
// Attributes: globals; name
func Slot(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("slot", attrs...)
}

// Small
// Description: Side comment.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Small(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("small", attrs...)
}

// Source
// Description: Image source for img or media source for video or audio.
// Categories: none.
// Parents: picture; video; audio.
// Children: empty.
// Attributes: globals; type; media; src; srcset; sizes; width; height
func Source(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("source", attrs...)
}

// Span
// Description: Generic phrasing container.
// Categories: flow; phrasing; palpable.
// Parents: phrasing; option element inner content elements*.
// Children: phrasing.
// Attributes: globals
func Span(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("span", attrs...)
}

// Strong
// Description: Importance.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Strong(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("strong", attrs...)
}

// Style
// Description: Embedded styling information.
// Categories: metadata.
// Parents: head; noscript*.
// Children: text*.
// Attributes: globals; media; blocking
func Style(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("style", attrs...)
}

// Sub
// Description: Subscript.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Sub(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("sub", attrs...)
}

// Summary
// Description: Caption for details.
// Categories: none.
// Parents: details.
// Children: phrasing; heading content.
// Attributes: globals
func Summary(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("summary", attrs...)
}

// Sup
// Description: Superscript.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Sup(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("sup", attrs...)
}

// Svg
// Description: SVG root.
// Categories: flow; phrasing; embedded; palpable.
// Parents: phrasing.
// Children: per [SVG].
// Attributes: per [SVG]
func Svg(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("svg", attrs...)
}

// Table
// Description: Table.
// Categories: flow; palpable.
// Parents: flow.
// Children: caption*; colgroup*; thead*; tbody*; tfoot*; tr*; script-supporting elements.
// Attributes: globals
func Table(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("table", attrs...)
}

// Tbody
// Description: Group of rows in a table.
// Categories: none.
// Parents: table.
// Children: tr; script-supporting elements.
// Attributes: globals
func Tbody(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("tbody", attrs...)
}

// Td
// Description: Table cell.
// Categories: none.
// Parents: tr.
// Children: flow.
// Attributes: globals; colspan; rowspan; headers
func Td(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("td", attrs...)
}

// Template
// Description: Template.
// Categories: metadata; flow; phrasing; script-supporting.
// Parents: metadata; phrasing; script-supporting; colgroup*.
// Children: empty.
// Attributes: globals; shadowrootmode; shadowrootdelegatesfocus; shadowrootclonable; shadowrootserializable; shadowrootcustomelementregistry
func Template(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("template", attrs...)
}

// Textarea
// Description: Multiline text controls.
// Categories: flow; phrasing; interactive; listed; labelable; submittable; resettable; form-associated; palpable.
// Parents: phrasing.
// Children: text.
// Attributes: globals; autocomplete; cols; dirname; disabled; form; maxlength; minlength; name; placeholder; readonly; required; rows; wrap
func Textarea(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("textarea", attrs...)
}

// Tfoot
// Description: Group of footer rows in a table.
// Categories: none.
// Parents: table.
// Children: tr; script-supporting elements.
// Attributes: globals
func Tfoot(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("tfoot", attrs...)
}

// Th
// Description: Table header cell.
// Categories: interactive*.
// Parents: tr.
// Children: flow*.
// Attributes: globals; colspan; rowspan; headers; scope; abbr
func Th(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("th", attrs...)
}

// Thead
// Description: Group of heading rows in a table.
// Categories: none.
// Parents: table.
// Children: tr; script-supporting elements.
// Attributes: globals
func Thead(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("thead", attrs...)
}

// Time
// Description: Machine-readable equivalent of date- or time-related data.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals; datetime
func Time(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("time", attrs...)
}

// Title
// Description: Document title.
// Categories: metadata.
// Parents: head.
// Children: text*.
// Attributes: globals
func Title(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("title", attrs...)
}

// Tr
// Description: Table row.
// Categories: none.
// Parents: table; thead; tbody; tfoot.
// Children: th*; td; script-supporting elements.
// Attributes: globals
func Tr(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("tr", attrs...)
}

// Track
// Description: Timed text track.
// Categories: none.
// Parents: audio; video.
// Children: empty.
// Attributes: globals; default; kind; label; src; srclang
func Track(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("track", attrs...)
}

// U
// Description: Unarticulated annotation.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func U(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("u", attrs...)
}

// Ul
// Description: List.
// Categories: flow; palpable*.
// Parents: flow.
// Children: li; script-supporting elements.
// Attributes: globals
func Ul(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("ul", attrs...)
}

// Var
// Description: Variable.
// Categories: flow; phrasing; palpable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Var(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("var", attrs...)
}

// Video
// Description: Video player.
// Categories: flow; phrasing; embedded; interactive; palpable.
// Parents: phrasing.
// Children: source*; track*; transparent*.
// Attributes: globals; src; crossorigin; poster; preload; autoplay; playsinline; loop; muted; controls; width; height
func Video(attrs ...doc.IAttribute) doc.ContContainerFunc {
	return doc.ParentElem("video", attrs...)
}

// Wbr
// Description: Line breaking opportunity.
// Categories: flow; phrasing.
// Parents: phrasing.
// Children: empty.
// Attributes: globals
func Wbr(attrs ...doc.IAttribute) doc.IContent {
	return doc.ChildElem("wbr", attrs...)
}
