// Code generated by "go run -C ../../generate ./"; DO NOT EDIT.
// HTML spec at https://html.spec.whatwg.org/multipage/indices.html

package attrs

import (
	"io"

	"github.com/ramonpetgrave64/go-html-compose/pkg/doc"
)

type Abbr struct {
	doc.IAttribute
	ThAttribute
}

func (a Abbr) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Accept struct {
	doc.IAttribute
	InputAttribute
}

func (a Accept) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type AcceptCharset struct {
	doc.IAttribute
	FormAttribute
}

func (a AcceptCharset) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Accesskey struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Accesskey) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Action struct {
	doc.IAttribute
	FormAttribute
}

func (a Action) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Allow struct {
	doc.IAttribute
	IframeAttribute
}

func (a Allow) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Allowfullscreen struct {
	doc.IAttribute
	IframeAttribute
}

func (a Allowfullscreen) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Alpha struct {
	doc.IAttribute
	InputAttribute
}

func (a Alpha) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Alt struct {
	doc.IAttribute
	AreaAttribute
	ImgAttribute
	InputAttribute
}

func (a Alt) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type As struct {
	doc.IAttribute
	LinkAttribute
}

func (a As) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Async struct {
	doc.IAttribute
	ScriptAttribute
}

func (a Async) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Autocapitalize struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Autocapitalize) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Autocomplete struct {
	doc.IAttribute
	FormAttribute
	InputAttribute
	SelectAttribute
	TextareaAttribute
}

func (a Autocomplete) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Autocorrect struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Autocorrect) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Autofocus struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Autofocus) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Autoplay struct {
	doc.IAttribute
	AudioAttribute
	VideoAttribute
}

func (a Autoplay) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Blocking struct {
	doc.IAttribute
	LinkAttribute
	ScriptAttribute
	StyleAttribute
}

func (a Blocking) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Charset struct {
	doc.IAttribute
	MetaAttribute
}

func (a Charset) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Checked struct {
	doc.IAttribute
	InputAttribute
}

func (a Checked) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Cite struct {
	doc.IAttribute
	BlockquoteAttribute
	DelAttribute
	InsAttribute
	QAttribute
}

func (a Cite) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Class struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Class) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Closedby struct {
	doc.IAttribute
	DialogAttribute
}

func (a Closedby) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Color struct {
	doc.IAttribute
	LinkAttribute
}

func (a Color) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Colorspace struct {
	doc.IAttribute
	InputAttribute
}

func (a Colorspace) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Cols struct {
	doc.IAttribute
	TextareaAttribute
}

func (a Cols) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Colspan struct {
	doc.IAttribute
	TdAttribute
	ThAttribute
}

func (a Colspan) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Command struct {
	doc.IAttribute
	ButtonAttribute
}

func (a Command) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Commandfor struct {
	doc.IAttribute
	ButtonAttribute
}

func (a Commandfor) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Content struct {
	doc.IAttribute
	MetaAttribute
}

func (a Content) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Contenteditable struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Contenteditable) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Controls struct {
	doc.IAttribute
	AudioAttribute
	VideoAttribute
}

func (a Controls) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Coords struct {
	doc.IAttribute
	AreaAttribute
}

func (a Coords) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Crossorigin struct {
	doc.IAttribute
	AudioAttribute
	ImgAttribute
	LinkAttribute
	ScriptAttribute
	VideoAttribute
}

func (a Crossorigin) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Data struct {
	doc.IAttribute
	ObjectAttribute
}

func (a Data) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Datetime struct {
	doc.IAttribute
	DelAttribute
	InsAttribute
	TimeAttribute
}

func (a Datetime) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Decoding struct {
	doc.IAttribute
	ImgAttribute
}

func (a Decoding) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Default struct {
	doc.IAttribute
	TrackAttribute
}

func (a Default) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Defer struct {
	doc.IAttribute
	ScriptAttribute
}

func (a Defer) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Dir struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Dir) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Dirname struct {
	doc.IAttribute
	InputAttribute
	TextareaAttribute
}

func (a Dirname) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Disabled struct {
	doc.IAttribute
	ButtonAttribute
	InputAttribute
	OptgroupAttribute
	OptionAttribute
	SelectAttribute
	TextareaAttribute
	FieldsetAttribute
	LinkAttribute
}

func (a Disabled) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Download struct {
	doc.IAttribute
	AAttribute
	AreaAttribute
}

func (a Download) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Draggable struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Draggable) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Enctype struct {
	doc.IAttribute
	FormAttribute
}

func (a Enctype) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Enterkeyhint struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Enterkeyhint) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Fetchpriority struct {
	doc.IAttribute
	ImgAttribute
	LinkAttribute
	ScriptAttribute
}

func (a Fetchpriority) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type For struct {
	doc.IAttribute
	LabelAttribute
	OutputAttribute
}

func (a For) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Form struct {
	doc.IAttribute
	ButtonAttribute
	FieldsetAttribute
	InputAttribute
	ObjectAttribute
	OutputAttribute
	SelectAttribute
	TextareaAttribute
}

func (a Form) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Formaction struct {
	doc.IAttribute
	ButtonAttribute
	InputAttribute
}

func (a Formaction) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Formenctype struct {
	doc.IAttribute
	ButtonAttribute
	InputAttribute
}

func (a Formenctype) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Formmethod struct {
	doc.IAttribute
	ButtonAttribute
	InputAttribute
}

func (a Formmethod) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Formnovalidate struct {
	doc.IAttribute
	ButtonAttribute
	InputAttribute
}

func (a Formnovalidate) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Formtarget struct {
	doc.IAttribute
	ButtonAttribute
	InputAttribute
}

func (a Formtarget) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Headers struct {
	doc.IAttribute
	TdAttribute
	ThAttribute
}

func (a Headers) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Height struct {
	doc.IAttribute
	CanvasAttribute
	EmbedAttribute
	IframeAttribute
	ImgAttribute
	InputAttribute
	ObjectAttribute
	SourceAttribute
	VideoAttribute
}

func (a Height) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Hidden struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Hidden) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type High struct {
	doc.IAttribute
	MeterAttribute
}

func (a High) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Href struct {
	doc.IAttribute
	AAttribute
	AreaAttribute
	LinkAttribute
	BaseAttribute
}

func (a Href) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Hreflang struct {
	doc.IAttribute
	AAttribute
	LinkAttribute
}

func (a Hreflang) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type HttpEquiv struct {
	doc.IAttribute
	MetaAttribute
}

func (a HttpEquiv) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Id struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Id) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Imagesizes struct {
	doc.IAttribute
	LinkAttribute
}

func (a Imagesizes) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Imagesrcset struct {
	doc.IAttribute
	LinkAttribute
}

func (a Imagesrcset) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Inert struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Inert) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Inputmode struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Inputmode) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Integrity struct {
	doc.IAttribute
	LinkAttribute
	ScriptAttribute
}

func (a Integrity) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Is struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Is) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ismap struct {
	doc.IAttribute
	ImgAttribute
}

func (a Ismap) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Itemid struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Itemid) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Itemprop struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Itemprop) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Itemref struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Itemref) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Itemscope struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Itemscope) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Itemtype struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Itemtype) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Kind struct {
	doc.IAttribute
	TrackAttribute
}

func (a Kind) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Label struct {
	doc.IAttribute
	OptgroupAttribute
	OptionAttribute
	TrackAttribute
}

func (a Label) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Lang struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Lang) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type List struct {
	doc.IAttribute
	InputAttribute
}

func (a List) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Loading struct {
	doc.IAttribute
	IframeAttribute
	ImgAttribute
}

func (a Loading) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Loop struct {
	doc.IAttribute
	AudioAttribute
	VideoAttribute
}

func (a Loop) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Low struct {
	doc.IAttribute
	MeterAttribute
}

func (a Low) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Max struct {
	doc.IAttribute
	InputAttribute
	MeterAttribute
	ProgressAttribute
}

func (a Max) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Maxlength struct {
	doc.IAttribute
	InputAttribute
	TextareaAttribute
}

func (a Maxlength) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Media struct {
	doc.IAttribute
	LinkAttribute
	MetaAttribute
	SourceAttribute
	StyleAttribute
}

func (a Media) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Method struct {
	doc.IAttribute
	FormAttribute
}

func (a Method) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Min struct {
	doc.IAttribute
	InputAttribute
	MeterAttribute
}

func (a Min) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Minlength struct {
	doc.IAttribute
	InputAttribute
	TextareaAttribute
}

func (a Minlength) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Multiple struct {
	doc.IAttribute
	InputAttribute
	SelectAttribute
}

func (a Multiple) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Muted struct {
	doc.IAttribute
	AudioAttribute
	VideoAttribute
}

func (a Muted) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Name struct {
	doc.IAttribute
	ButtonAttribute
	FieldsetAttribute
	InputAttribute
	OutputAttribute
	SelectAttribute
	TextareaAttribute
	DetailsAttribute
	FormAttribute
	IframeAttribute
	ObjectAttribute
	MapAttribute
	MetaAttribute
	SlotAttribute
}

func (a Name) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Nomodule struct {
	doc.IAttribute
	ScriptAttribute
}

func (a Nomodule) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Nonce struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Nonce) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Novalidate struct {
	doc.IAttribute
	FormAttribute
}

func (a Novalidate) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Open struct {
	doc.IAttribute
	DetailsAttribute
	DialogAttribute
}

func (a Open) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Optimum struct {
	doc.IAttribute
	MeterAttribute
}

func (a Optimum) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Pattern struct {
	doc.IAttribute
	InputAttribute
}

func (a Pattern) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ping struct {
	doc.IAttribute
	AAttribute
	AreaAttribute
}

func (a Ping) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Placeholder struct {
	doc.IAttribute
	InputAttribute
	TextareaAttribute
}

func (a Placeholder) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Playsinline struct {
	doc.IAttribute
	VideoAttribute
}

func (a Playsinline) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Popover struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Popover) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Popovertarget struct {
	doc.IAttribute
	ButtonAttribute
	InputAttribute
}

func (a Popovertarget) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Popovertargetaction struct {
	doc.IAttribute
	ButtonAttribute
	InputAttribute
}

func (a Popovertargetaction) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Poster struct {
	doc.IAttribute
	VideoAttribute
}

func (a Poster) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Preload struct {
	doc.IAttribute
	AudioAttribute
	VideoAttribute
}

func (a Preload) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Readonly struct {
	doc.IAttribute
	InputAttribute
	TextareaAttribute
}

func (a Readonly) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Referrerpolicy struct {
	doc.IAttribute
	AAttribute
	AreaAttribute
	IframeAttribute
	ImgAttribute
	LinkAttribute
	ScriptAttribute
}

func (a Referrerpolicy) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Rel struct {
	doc.IAttribute
	AAttribute
	AreaAttribute
	LinkAttribute
}

func (a Rel) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Required struct {
	doc.IAttribute
	InputAttribute
	SelectAttribute
	TextareaAttribute
}

func (a Required) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Reversed struct {
	doc.IAttribute
	OlAttribute
}

func (a Reversed) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Rows struct {
	doc.IAttribute
	TextareaAttribute
}

func (a Rows) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Rowspan struct {
	doc.IAttribute
	TdAttribute
	ThAttribute
}

func (a Rowspan) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Sandbox struct {
	doc.IAttribute
	IframeAttribute
}

func (a Sandbox) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Scope struct {
	doc.IAttribute
	ThAttribute
}

func (a Scope) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Selected struct {
	doc.IAttribute
	OptionAttribute
}

func (a Selected) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Shadowrootclonable struct {
	doc.IAttribute
	TemplateAttribute
}

func (a Shadowrootclonable) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Shadowrootcustomelementregistry struct {
	doc.IAttribute
	TemplateAttribute
}

func (a Shadowrootcustomelementregistry) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Shadowrootdelegatesfocus struct {
	doc.IAttribute
	TemplateAttribute
}

func (a Shadowrootdelegatesfocus) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Shadowrootmode struct {
	doc.IAttribute
	TemplateAttribute
}

func (a Shadowrootmode) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Shadowrootserializable struct {
	doc.IAttribute
	TemplateAttribute
}

func (a Shadowrootserializable) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Shape struct {
	doc.IAttribute
	AreaAttribute
}

func (a Shape) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Size struct {
	doc.IAttribute
	InputAttribute
	SelectAttribute
}

func (a Size) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Sizes struct {
	doc.IAttribute
	LinkAttribute
	ImgAttribute
	SourceAttribute
}

func (a Sizes) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Slot struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Slot) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Span struct {
	doc.IAttribute
	ColAttribute
	ColgroupAttribute
}

func (a Span) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Spellcheck struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Spellcheck) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Src struct {
	doc.IAttribute
	AudioAttribute
	EmbedAttribute
	IframeAttribute
	ImgAttribute
	InputAttribute
	ScriptAttribute
	SourceAttribute
	TrackAttribute
	VideoAttribute
}

func (a Src) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Srcdoc struct {
	doc.IAttribute
	IframeAttribute
}

func (a Srcdoc) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Srclang struct {
	doc.IAttribute
	TrackAttribute
}

func (a Srclang) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Srcset struct {
	doc.IAttribute
	ImgAttribute
	SourceAttribute
}

func (a Srcset) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Start struct {
	doc.IAttribute
	OlAttribute
}

func (a Start) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Step struct {
	doc.IAttribute
	InputAttribute
}

func (a Step) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Style struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Style) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Tabindex struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Tabindex) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Target struct {
	doc.IAttribute
	AAttribute
	AreaAttribute
	BaseAttribute
	FormAttribute
}

func (a Target) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Title struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Title) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Translate struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Translate) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Type struct {
	doc.IAttribute
	AAttribute
	LinkAttribute
	ButtonAttribute
	EmbedAttribute
	ObjectAttribute
	SourceAttribute
	InputAttribute
	OlAttribute
	ScriptAttribute
}

func (a Type) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Usemap struct {
	doc.IAttribute
	ImgAttribute
}

func (a Usemap) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Value struct {
	doc.IAttribute
	ButtonAttribute
	OptionAttribute
	DataAttribute
	InputAttribute
	LiAttribute
	MeterAttribute
	ProgressAttribute
}

func (a Value) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Width struct {
	doc.IAttribute
	CanvasAttribute
	EmbedAttribute
	IframeAttribute
	ImgAttribute
	InputAttribute
	ObjectAttribute
	SourceAttribute
	VideoAttribute
}

func (a Width) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Wrap struct {
	doc.IAttribute
	TextareaAttribute
}

func (a Wrap) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Writingsuggestions struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Writingsuggestions) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onafterprint struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onafterprint) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onauxclick struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onauxclick) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onbeforeinput struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onbeforeinput) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onbeforematch struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onbeforematch) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onbeforeprint struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onbeforeprint) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onbeforeunload struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onbeforeunload) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onbeforetoggle struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onbeforetoggle) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onblur struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onblur) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Oncancel struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Oncancel) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Oncanplay struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Oncanplay) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Oncanplaythrough struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Oncanplaythrough) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onchange struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onchange) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onclick struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onclick) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onclose struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onclose) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Oncommand struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Oncommand) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Oncontextlost struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Oncontextlost) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Oncontextmenu struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Oncontextmenu) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Oncontextrestored struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Oncontextrestored) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Oncopy struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Oncopy) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Oncuechange struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Oncuechange) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Oncut struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Oncut) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ondblclick struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Ondblclick) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ondrag struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Ondrag) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ondragend struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Ondragend) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ondragenter struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Ondragenter) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ondragleave struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Ondragleave) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ondragover struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Ondragover) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ondragstart struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Ondragstart) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ondrop struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Ondrop) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ondurationchange struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Ondurationchange) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onemptied struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onemptied) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onended struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onended) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onerror struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onerror) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onfocus struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onfocus) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onformdata struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onformdata) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onhashchange struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onhashchange) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Oninput struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Oninput) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Oninvalid struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Oninvalid) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onkeydown struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onkeydown) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onkeypress struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onkeypress) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onkeyup struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onkeyup) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onlanguagechange struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onlanguagechange) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onload struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onload) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onloadeddata struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onloadeddata) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onloadedmetadata struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onloadedmetadata) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onloadstart struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onloadstart) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onmessage struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onmessage) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onmessageerror struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onmessageerror) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onmousedown struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onmousedown) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onmouseenter struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onmouseenter) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onmouseleave struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onmouseleave) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onmousemove struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onmousemove) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onmouseout struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onmouseout) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onmouseover struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onmouseover) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onmouseup struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onmouseup) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onoffline struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onoffline) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ononline struct {
	doc.IAttribute
	BodyAttribute
}

func (a Ononline) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onpagehide struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onpagehide) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onpagereveal struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onpagereveal) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onpageshow struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onpageshow) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onpageswap struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onpageswap) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onpaste struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onpaste) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onpause struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onpause) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onplay struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onplay) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onplaying struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onplaying) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onpopstate struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onpopstate) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onprogress struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onprogress) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onratechange struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onratechange) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onreset struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onreset) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onresize struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onresize) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onrejectionhandled struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onrejectionhandled) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onscroll struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onscroll) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onscrollend struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onscrollend) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onsecuritypolicyviolation struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onsecuritypolicyviolation) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onseeked struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onseeked) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onseeking struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onseeking) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onselect struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onselect) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onslotchange struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onslotchange) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onstalled struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onstalled) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onstorage struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onstorage) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onsubmit struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onsubmit) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onsuspend struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onsuspend) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ontimeupdate struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Ontimeupdate) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Ontoggle struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Ontoggle) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onunhandledrejection struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onunhandledrejection) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onunload struct {
	doc.IAttribute
	BodyAttribute
}

func (a Onunload) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onvolumechange struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onvolumechange) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onwaiting struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onwaiting) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}

type Onwheel struct {
	doc.IAttribute
	GlobalAttribute
}

func (a Onwheel) RenderAttr(wr io.Writer) (err error) {
	return a.IAttribute.RenderAttr(wr)
}
