// Code generated by "go run -C ../generate ./cmd/generate/"; DO NOT EDIT.
// HTML spec at https://html.spec.whatwg.org/multipage/indices.html

package tags

import "go-html-compose/pkg/attr"
import "go-html-compose/pkg/tag"

// Special Elements

// Doctype is a required preamble.
var Doctype = tag.UnitTag("!DOCTYPE html")

// Regular Elements

// A
// Description: Hyperlink.
// Parents: phrasing.
// Children: transparent*.
// Attributes: globals; href; target; download; ping; rel; hreflang; type; referrerpolicy
func A(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("a", attrs...)
}

// Abbr
// Description: Abbreviation.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Abbr(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("abbr", attrs...)
}

// Address
// Description: Contact information for a page or article element.
// Parents: flow.
// Children: flow*.
// Attributes: globals
func Address(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("address", attrs...)
}

// Area
// Description: Hyperlink or dead area on an image map.
// Parents: phrasing*.
// Children: empty.
// Attributes: globals; alt; coords; shape; href; target; download; ping; rel; referrerpolicy
func Area(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("area", attrs...)
}

// Article
// Description: Self-contained syndicatable or reusable composition.
// Parents: flow.
// Children: flow.
// Attributes: globals
func Article(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("article", attrs...)
}

// Aside
// Description: Sidebar for tangentially related content.
// Parents: flow.
// Children: flow.
// Attributes: globals
func Aside(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("aside", attrs...)
}

// Audio
// Description: Audio player.
// Parents: phrasing.
// Children: source*; track*; transparent*.
// Attributes: globals; src; crossorigin; preload; autoplay; loop; muted; controls
func Audio(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("audio", attrs...)
}

// B
// Description: Keywords.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func B(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("b", attrs...)
}

// Base
// Description: Base URL and default target navigable for hyperlinks and forms.
// Parents: head.
// Children: empty.
// Attributes: globals; href; target
func Base(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("base", attrs...)
}

// Bdi
// Description: Text directionality isolation.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Bdi(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("bdi", attrs...)
}

// Bdo
// Description: Text directionality formatting.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Bdo(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("bdo", attrs...)
}

// Blockquote
// Description: A section quoted from another source.
// Parents: flow.
// Children: flow.
// Attributes: globals; cite
func Blockquote(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("blockquote", attrs...)
}

// Body
// Description: Document body.
// Parents: html.
// Children: flow.
// Attributes: globals; onafterprint; onbeforeprint; onbeforeunload; onhashchange; onlanguagechange; onmessage; onmessageerror; onoffline; ononline; onpageswap; onpagehide; onpagereveal; onpageshow; onpopstate; onrejectionhandled; onstorage; onunhandledrejection; onunload
func Body(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("body", attrs...)
}

// Br
// Description: Line break, e.g. in poem or postal address.
// Parents: phrasing.
// Children: empty.
// Attributes: globals
func Br(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("br", attrs...)
}

// Button
// Description: Button control.
// Parents: phrasing.
// Children: phrasing*.
// Attributes: globals; command; commandfor; disabled; form; formaction; formenctype; formmethod; formnovalidate; formtarget; name; popovertarget; popovertargetaction; type; value
func Button(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("button", attrs...)
}

// Canvas
// Description: Scriptable bitmap canvas.
// Parents: phrasing.
// Children: transparent.
// Attributes: globals; width; height
func Canvas(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("canvas", attrs...)
}

// Caption
// Description: Table caption.
// Parents: table.
// Children: flow*.
// Attributes: globals
func Caption(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("caption", attrs...)
}

// Cite
// Description: Title of a work.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Cite(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("cite", attrs...)
}

// Code
// Description: Computer code.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Code(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("code", attrs...)
}

// Col
// Description: Table column.
// Parents: colgroup.
// Children: empty.
// Attributes: globals; span
func Col(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("col", attrs...)
}

// Colgroup
// Description: Group of columns in a table.
// Parents: table.
// Children: col*; template*.
// Attributes: globals; span
func Colgroup(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("colgroup", attrs...)
}

// Data
// Description: Machine-readable equivalent.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals; value
func Data(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("data", attrs...)
}

// Datalist
// Description: Container for options for combo box control.
// Parents: phrasing.
// Children: phrasing*; option*; script-supporting elements*.
// Attributes: globals
func Datalist(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("datalist", attrs...)
}

// Dd
// Description: Content for corresponding dt element(s).
// Parents: dl; div*.
// Children: flow.
// Attributes: globals
func Dd(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("dd", attrs...)
}

// Del
// Description: A removal from the document.
// Parents: phrasing.
// Children: transparent.
// Attributes: globals; cite; datetime
func Del(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("del", attrs...)
}

// Details
// Description: Disclosure control for hiding details.
// Parents: flow.
// Children: summary*; flow.
// Attributes: globals; name; open
func Details(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("details", attrs...)
}

// Dfn
// Description: Defining instance.
// Parents: phrasing.
// Children: phrasing*.
// Attributes: globals
func Dfn(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("dfn", attrs...)
}

// Dialog
// Description: Dialog box or window.
// Parents: flow.
// Children: flow.
// Attributes: globals; open
func Dialog(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("dialog", attrs...)
}

// Div
// Description: Generic flow container, or container for name-value groups in dl elements.
// Parents: flow; dl.
// Children: flow.
// Attributes: globals
func Div(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("div", attrs...)
}

// Dl
// Description: Association list consisting of zero or more name-value groups.
// Parents: flow.
// Children: dt*; dd*; div*; script-supporting elements.
// Attributes: globals
func Dl(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("dl", attrs...)
}

// Dt
// Description: Legend for corresponding dd element(s).
// Parents: dl; div*.
// Children: flow*.
// Attributes: globals
func Dt(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("dt", attrs...)
}

// Em
// Description: Stress emphasis.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Em(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("em", attrs...)
}

// Embed
// Description: Plugin.
// Parents: phrasing.
// Children: empty.
// Attributes: globals; src; type; width; height; any*
func Embed(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("embed", attrs...)
}

// Fieldset
// Description: Group of form controls.
// Parents: flow.
// Children: legend*; flow.
// Attributes: globals; disabled; form; name
func Fieldset(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("fieldset", attrs...)
}

// Figcaption
// Description: Caption for figure.
// Parents: figure.
// Children: flow.
// Attributes: globals
func Figcaption(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("figcaption", attrs...)
}

// Figure
// Description: Figure with optional caption.
// Parents: flow.
// Children: figcaption*; flow.
// Attributes: globals
func Figure(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("figure", attrs...)
}

// Footer
// Description: Footer for a page or section.
// Parents: flow.
// Children: flow*.
// Attributes: globals
func Footer(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("footer", attrs...)
}

// Form
// Description: User-submittable form.
// Parents: flow.
// Children: flow*.
// Attributes: globals; accept-charset; action; autocomplete; enctype; method; name; novalidate; rel; target
func Form(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("form", attrs...)
}

// H1
// Description: Heading.
// Parents: legend; summary; flow.
// Children: phrasing.
// Attributes: globals
func H1(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("h1", attrs...)
}

// H2
// Description: Heading.
// Parents: legend; summary; flow.
// Children: phrasing.
// Attributes: globals
func H2(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("h2", attrs...)
}

// H3
// Description: Heading.
// Parents: legend; summary; flow.
// Children: phrasing.
// Attributes: globals
func H3(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("h3", attrs...)
}

// H4
// Description: Heading.
// Parents: legend; summary; flow.
// Children: phrasing.
// Attributes: globals
func H4(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("h4", attrs...)
}

// H5
// Description: Heading.
// Parents: legend; summary; flow.
// Children: phrasing.
// Attributes: globals
func H5(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("h5", attrs...)
}

// H6
// Description: Heading.
// Parents: legend; summary; flow.
// Children: phrasing.
// Attributes: globals
func H6(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("h6", attrs...)
}

// Head
// Description: Container for document metadata.
// Parents: html.
// Children: metadata content*.
// Attributes: globals
func Head(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("head", attrs...)
}

// Header
// Description: Introductory or navigational aids for a page or section.
// Parents: flow.
// Children: flow*.
// Attributes: globals
func Header(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("header", attrs...)
}

// Hgroup
// Description: Heading container.
// Parents: legend; summary; flow.
// Children: h1; h2; h3; h4; h5; h6; script-supporting elements.
// Attributes: globals
func Hgroup(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("hgroup", attrs...)
}

// Hr
// Description: Thematic break.
// Parents: flow.
// Children: empty.
// Attributes: globals
func Hr(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("hr", attrs...)
}

// Html
// Description: Root element.
// Parents: none*.
// Children: head*; body*.
// Attributes: globals
func Html(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("html", attrs...)
}

// I
// Description: Alternate voice.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func I(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("i", attrs...)
}

// Iframe
// Description: Child navigable.
// Parents: phrasing.
// Children: empty.
// Attributes: globals; src; srcdoc; name; sandbox; allow; allowfullscreen; width; height; referrerpolicy; loading
func Iframe(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("iframe", attrs...)
}

// Img
// Description: Image.
// Parents: phrasing; picture.
// Children: empty.
// Attributes: globals; alt; src; srcset; sizes; crossorigin; usemap; ismap; width; height; referrerpolicy; decoding; loading; fetchpriority
func Img(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("img", attrs...)
}

// Input
// Description: Form control.
// Parents: phrasing.
// Children: empty.
// Attributes: globals; accept; alpha; alt; autocomplete; checked; colorspace; dirname; disabled; form; formaction; formenctype; formmethod; formnovalidate; formtarget; height; list; max; maxlength; min; minlength; multiple; name; pattern; placeholder; popovertarget; popovertargetaction; readonly; required; size; src; step; type; value; width
func Input(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("input", attrs...)
}

// Ins
// Description: An addition to the document.
// Parents: phrasing.
// Children: transparent.
// Attributes: globals; cite; datetime
func Ins(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("ins", attrs...)
}

// Kbd
// Description: User input.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Kbd(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("kbd", attrs...)
}

// Label
// Description: Caption for a form control.
// Parents: phrasing.
// Children: phrasing*.
// Attributes: globals; for
func Label(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("label", attrs...)
}

// Legend
// Description: Caption for fieldset.
// Parents: fieldset.
// Children: phrasing; heading content.
// Attributes: globals
func Legend(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("legend", attrs...)
}

// Li
// Description: List item.
// Parents: ol; ul; menu*.
// Children: flow.
// Attributes: globals; value*
func Li(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("li", attrs...)
}

// Link
// Description: Link metadata.
// Parents: head; noscript*; phrasing*.
// Children: empty.
// Attributes: globals; href; crossorigin; rel; as; media; hreflang; type; sizes; imagesrcset; imagesizes; referrerpolicy; integrity; blocking; color; disabled; fetchpriority
func Link(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("link", attrs...)
}

// Main
// Description: Container for the dominant contents of the document.
// Parents: flow*.
// Children: flow.
// Attributes: globals
func Main(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("main", attrs...)
}

// Map
// Description: Image map.
// Parents: phrasing.
// Children: transparent; area*.
// Attributes: globals; name
func Map(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("map", attrs...)
}

// Mark
// Description: Highlight.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Mark(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("mark", attrs...)
}

// Math
// Description: MathML root.
// Parents: phrasing.
// Children: per [MATHML].
// Attributes: per [MATHML]
func Math(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("math", attrs...)
}

// Menu
// Description: Menu of commands.
// Parents: flow.
// Children: li; script-supporting elements.
// Attributes: globals
func Menu(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("menu", attrs...)
}

// Meta
// Description: Text metadata.
// Parents: head; noscript*; phrasing*.
// Children: empty.
// Attributes: globals; name; http-equiv; content; charset; media
func Meta(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("meta", attrs...)
}

// Meter
// Description: Gauge.
// Parents: phrasing.
// Children: phrasing*.
// Attributes: globals; value; min; max; low; high; optimum
func Meter(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("meter", attrs...)
}

// Nav
// Description: Section with navigational links.
// Parents: flow.
// Children: flow.
// Attributes: globals
func Nav(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("nav", attrs...)
}

// Noscript
// Description: Fallback content for script.
// Parents: head*; phrasing*.
// Children: varies*.
// Attributes: globals
func Noscript(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("noscript", attrs...)
}

// Object
// Description: Image, child navigable, or plugin.
// Parents: phrasing.
// Children: transparent.
// Attributes: globals; data; type; name; form; width; height
func Object(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("object", attrs...)
}

// Ol
// Description: Ordered list.
// Parents: flow.
// Children: li; script-supporting elements.
// Attributes: globals; reversed; start; type
func Ol(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("ol", attrs...)
}

// Optgroup
// Description: Group of options in a list box.
// Parents: select.
// Children: option; script-supporting elements.
// Attributes: globals; disabled; label
func Optgroup(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("optgroup", attrs...)
}

// Option
// Description: Option in a list box or combo box control.
// Parents: select; datalist; optgroup.
// Children: text*.
// Attributes: globals; disabled; label; selected; value
func Option(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("option", attrs...)
}

// Output
// Description: Calculated output value.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals; for; form; name
func Output(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("output", attrs...)
}

// P
// Description: Paragraph.
// Parents: flow.
// Children: phrasing.
// Attributes: globals
func P(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("p", attrs...)
}

// Picture
// Description: Image.
// Parents: phrasing.
// Children: source*; one img; script-supporting elements.
// Attributes: globals
func Picture(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("picture", attrs...)
}

// Pre
// Description: Block of preformatted text.
// Parents: flow.
// Children: phrasing.
// Attributes: globals
func Pre(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("pre", attrs...)
}

// Progress
// Description: Progress bar.
// Parents: phrasing.
// Children: phrasing*.
// Attributes: globals; value; max
func Progress(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("progress", attrs...)
}

// Q
// Description: Quotation.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals; cite
func Q(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("q", attrs...)
}

// Rp
// Description: Parenthesis for ruby annotation text.
// Parents: ruby.
// Children: text.
// Attributes: globals
func Rp(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("rp", attrs...)
}

// Rt
// Description: Ruby annotation text.
// Parents: ruby.
// Children: phrasing.
// Attributes: globals
func Rt(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("rt", attrs...)
}

// Ruby
// Description: Ruby annotation(s).
// Parents: phrasing.
// Children: phrasing; rt; rp*.
// Attributes: globals
func Ruby(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("ruby", attrs...)
}

// S
// Description: Inaccurate text.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func S(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("s", attrs...)
}

// Samp
// Description: Computer output.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Samp(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("samp", attrs...)
}

// Script
// Description: Embedded script.
// Parents: head; phrasing; script-supporting.
// Children: script, data, or script documentation*.
// Attributes: globals; src; type; nomodule; async; defer; crossorigin; integrity; referrerpolicy; blocking; fetchpriority
func Script(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("script", attrs...)
}

// Search
// Description: Container for search controls.
// Parents: flow.
// Children: flow.
// Attributes: globals
func Search(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("search", attrs...)
}

// Section
// Description: Generic document or application section.
// Parents: flow.
// Children: flow.
// Attributes: globals
func Section(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("section", attrs...)
}

// Select
// Description: List box control.
// Parents: phrasing.
// Children: option; optgroup; script-supporting elements.
// Attributes: globals; autocomplete; disabled; form; multiple; name; required; size
func Select(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("select", attrs...)
}

// Slot
// Description: Shadow tree slot.
// Parents: phrasing.
// Children: transparent.
// Attributes: globals; name
func Slot(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("slot", attrs...)
}

// Small
// Description: Side comment.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Small(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("small", attrs...)
}

// Source
// Description: Image source for img or media source for video or audio.
// Parents: picture; video; audio.
// Children: empty.
// Attributes: globals; type; media; src; srcset; sizes; width; height
func Source(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("source", attrs...)
}

// Span
// Description: Generic phrasing container.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Span(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("span", attrs...)
}

// Strong
// Description: Importance.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Strong(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("strong", attrs...)
}

// Style
// Description: Embedded styling information.
// Parents: head; noscript*.
// Children: text*.
// Attributes: globals; media; blocking
func Style(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("style", attrs...)
}

// Sub
// Description: Subscript.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Sub(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("sub", attrs...)
}

// Summary
// Description: Caption for details.
// Parents: details.
// Children: phrasing; heading content.
// Attributes: globals
func Summary(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("summary", attrs...)
}

// Sup
// Description: Superscript.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Sup(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("sup", attrs...)
}

// Svg
// Description: SVG root.
// Parents: phrasing.
// Children: per [SVG].
// Attributes: per [SVG]
func Svg(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("svg", attrs...)
}

// Table
// Description: Table.
// Parents: flow.
// Children: caption*; colgroup*; thead*; tbody*; tfoot*; tr*; script-supporting elements.
// Attributes: globals
func Table(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("table", attrs...)
}

// Tbody
// Description: Group of rows in a table.
// Parents: table.
// Children: tr; script-supporting elements.
// Attributes: globals
func Tbody(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("tbody", attrs...)
}

// Td
// Description: Table cell.
// Parents: tr.
// Children: flow.
// Attributes: globals; colspan; rowspan; headers
func Td(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("td", attrs...)
}

// Template
// Description: Template.
// Parents: metadata; phrasing; script-supporting; colgroup*.
// Children: empty.
// Attributes: globals; shadowrootmode; shadowrootdelegatesfocus; shadowrootclonable; shadowrootserializable
func Template(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("template", attrs...)
}

// Textarea
// Description: Multiline text controls.
// Parents: phrasing.
// Children: text.
// Attributes: globals; autocomplete; cols; dirname; disabled; form; maxlength; minlength; name; placeholder; readonly; required; rows; wrap
func Textarea(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("textarea", attrs...)
}

// Tfoot
// Description: Group of footer rows in a table.
// Parents: table.
// Children: tr; script-supporting elements.
// Attributes: globals
func Tfoot(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("tfoot", attrs...)
}

// Th
// Description: Table header cell.
// Parents: tr.
// Children: flow*.
// Attributes: globals; colspan; rowspan; headers; scope; abbr
func Th(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("th", attrs...)
}

// Thead
// Description: Group of heading rows in a table.
// Parents: table.
// Children: tr; script-supporting elements.
// Attributes: globals
func Thead(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("thead", attrs...)
}

// Time
// Description: Machine-readable equivalent of date- or time-related data.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals; datetime
func Time(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("time", attrs...)
}

// Title
// Description: Document title.
// Parents: head.
// Children: text*.
// Attributes: globals
func Title(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("title", attrs...)
}

// Tr
// Description: Table row.
// Parents: table; thead; tbody; tfoot.
// Children: th*; td; script-supporting elements.
// Attributes: globals
func Tr(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("tr", attrs...)
}

// Track
// Description: Timed text track.
// Parents: audio; video.
// Children: empty.
// Attributes: globals; default; kind; label; src; srclang
func Track(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("track", attrs...)
}

// U
// Description: Unarticulated annotation.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func U(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("u", attrs...)
}

// Ul
// Description: List.
// Parents: flow.
// Children: li; script-supporting elements.
// Attributes: globals
func Ul(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("ul", attrs...)
}

// Var
// Description: Variable.
// Parents: phrasing.
// Children: phrasing.
// Attributes: globals
func Var(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("var", attrs...)
}

// Video
// Description: Video player.
// Parents: phrasing.
// Children: source*; track*; transparent*.
// Attributes: globals; src; crossorigin; poster; preload; autoplay; playsinline; loop; muted; controls; width; height
func Video(attrs ...*attr.AttributeStruct) tag.ContentFunc {
	return tag.ParentTag("video", attrs...)
}

// Wbr
// Description: Line breaking opportunity.
// Parents: phrasing.
// Children: empty.
// Attributes: globals
func Wbr(attrs ...*attr.AttributeStruct) *tag.UnitTagStruct {
	return tag.UnitTag("wbr", attrs...)
}
