// Code generated by "go run -C ../../generate ./"; DO NOT EDIT.
// HTML spec at https://html.spec.whatwg.org/multipage/indices.html

package attrs

import (
	"github.com/ramonpetgrave64/go-html-compose/pkg/html/attrs"
	types "github.com/ramonpetgrave64/go-html-compose/pkg/html/strict/internal/types/attrs"
)

// Abbr
//
// Element(s): th.
//
// Description: Alternative label to use for the header cell when referencing the cell in other contexts.
//
// Value: Text*.
func Abbr(value string) types.Abbr {
	return types.Abbr{IAttribute: attrs.Abbr(value)}
}

// Accept
//
// Element(s): input.
//
// Description: Hint for expected file type in file upload controls.
//
// Value: Set of comma-separated tokens* consisting of valid MIME type strings with no parameters or audio/*, video/*, or image/*.
func Accept(value string) types.Accept {
	return types.Accept{IAttribute: attrs.Accept(value)}
}

// AcceptCharset
//
// Element(s): form.
//
// Description: Character encodings to use for form submission.
//
// Value: ASCII case-insensitive match for "UTF-8".
func AcceptCharset(value string) types.AcceptCharset {
	return types.AcceptCharset{IAttribute: attrs.AcceptCharset(value)}
}

// Accesskey
//
// Element(s): HTML elements.
//
// Description: Keyboard shortcut to activate or focus element.
//
// Value: Ordered set of unique space-separated tokens, none of which are identical to another, each consisting of one code point in length.
func Accesskey(value string) types.Accesskey {
	return types.Accesskey{IAttribute: attrs.Accesskey(value)}
}

// Action
//
// Element(s): form.
//
// Description: URL to use for form submission.
//
// Value: Valid non-empty URL potentially surrounded by spaces.
func Action(value string) types.Action {
	return types.Action{IAttribute: attrs.Action(value)}
}

// Allow
//
// Element(s): iframe.
//
// Description: Permissions policy to be applied to the iframe's contents.
//
// Value: Serialized permissions policy.
func Allow(value string) types.Allow {
	return types.Allow{IAttribute: attrs.Allow(value)}
}

// Allowfullscreen
//
// Element(s): iframe.
//
// Description: Whether to allow the iframe's contents to use requestFullscreen().
//
// Value: Boolean attribute.
func Allowfullscreen(value bool) types.Allowfullscreen {
	return types.Allowfullscreen{IAttribute: attrs.Allowfullscreen(value)}
}

// Alpha
//
// Element(s): input.
//
// Description: Allow the color's alpha component to be set.
//
// Value: Boolean attribute.
func Alpha(value bool) types.Alpha {
	return types.Alpha{IAttribute: attrs.Alpha(value)}
}

// Alt
//
// Element(s): area; img; input.
//
// Description: Replacement text for use when images are not available.
//
// Value: Text*.
func Alt(value string) types.Alt {
	return types.Alt{IAttribute: attrs.Alt(value)}
}

// As
//
// Element(s): link.
//
// Description: Potential destination for a preload request (for rel="preload" and rel="modulepreload").
//
// Value: Potential destination, for rel="preload"; script-like destination, for rel="modulepreload".
func As(value string) types.As {
	return types.As{IAttribute: attrs.As(value)}
}

// Async
//
// Element(s): script.
//
// Description: Execute script when available, without blocking while fetching.
//
// Value: Boolean attribute.
func Async(value bool) types.Async {
	return types.Async{IAttribute: attrs.Async(value)}
}

// Autocapitalize
//
// Element(s): HTML elements.
//
// Description: Recommended autocapitalization behavior (for supported input methods).
//
// Value: "on"; "off"; "none"; "sentences"; "words"; "characters".
func Autocapitalize(value string) types.Autocapitalize {
	return types.Autocapitalize{IAttribute: attrs.Autocapitalize(value)}
}

// Autocomplete
//
// Element(s): form.
//
// Description: Default setting for autofill feature for controls in the form.
//
// Value: "on"; "off".
//
// Element(s): input; select; textarea.
//
// Description: Hint for form autofill feature.
//
// Value: Autofill field name and related tokens*.
func Autocomplete(value string) types.Autocomplete {
	return types.Autocomplete{IAttribute: attrs.Autocomplete(value)}
}

// Autocorrect
//
// Element(s): HTML elements.
//
// Description: Recommended autocorrection behavior (for supported input methods).
//
// Value: "on"; "off".
func Autocorrect(value string) types.Autocorrect {
	return types.Autocorrect{IAttribute: attrs.Autocorrect(value)}
}

// Autofocus
//
// Element(s): HTML elements.
//
// Description: Automatically focus the element when the page is loaded.
//
// Value: Boolean attribute.
func Autofocus(value bool) types.Autofocus {
	return types.Autofocus{IAttribute: attrs.Autofocus(value)}
}

// Autoplay
//
// Element(s): audio; video.
//
// Description: Hint that the media resource can be started automatically when the page is loaded.
//
// Value: Boolean attribute.
func Autoplay(value bool) types.Autoplay {
	return types.Autoplay{IAttribute: attrs.Autoplay(value)}
}

// Blocking
//
// Element(s): link; script; style.
//
// Description: Whether the element is potentially render-blocking.
//
// Value: Unordered set of unique space-separated tokens*.
func Blocking(value string) types.Blocking {
	return types.Blocking{IAttribute: attrs.Blocking(value)}
}

// Charset
//
// Element(s): meta.
//
// Description: Character encoding declaration.
//
// Value: "utf-8".
func Charset(value string) types.Charset {
	return types.Charset{IAttribute: attrs.Charset(value)}
}

// Checked
//
// Element(s): input.
//
// Description: Whether the control is checked.
//
// Value: Boolean attribute.
func Checked(value bool) types.Checked {
	return types.Checked{IAttribute: attrs.Checked(value)}
}

// Cite
//
// Element(s): blockquote; del; ins; q.
//
// Description: Link to the source of the quotation or more information about the edit.
//
// Value: Valid URL potentially surrounded by spaces.
func Cite(value string) types.Cite {
	return types.Cite{IAttribute: attrs.Cite(value)}
}

// Class
//
// Element(s): HTML elements.
//
// Description: Classes to which the element belongs.
//
// Value: Set of space-separated tokens.
func Class(value string) types.Class {
	return types.Class{IAttribute: attrs.Class(value)}
}

// Closedby
//
// Element(s): dialog.
//
// Description: Which user actions will close the dialog.
//
// Value: "any"; "closerequest"; "none";.
func Closedby(value string) types.Closedby {
	return types.Closedby{IAttribute: attrs.Closedby(value)}
}

// Color
//
// Element(s): link.
//
// Description: Color to use when customizing a site's icon (for rel="mask-icon").
//
// Value: CSS <color>.
func Color(value string) types.Color {
	return types.Color{IAttribute: attrs.Color(value)}
}

// Colorspace
//
// Element(s): input.
//
// Description: The color space of the serialized color.
//
// Value: "limited-srgb"; "display-p3".
func Colorspace(value string) types.Colorspace {
	return types.Colorspace{IAttribute: attrs.Colorspace(value)}
}

// Cols
//
// Element(s): textarea.
//
// Description: Maximum number of characters per line.
//
// Value: Valid non-negative integer greater than zero.
func Cols(value string) types.Cols {
	return types.Cols{IAttribute: attrs.Cols(value)}
}

// Colspan
//
// Element(s): td; th.
//
// Description: Number of columns that the cell is to span.
//
// Value: Valid non-negative integer greater than zero.
func Colspan(value string) types.Colspan {
	return types.Colspan{IAttribute: attrs.Colspan(value)}
}

// Command
//
// Element(s): button.
//
// Description: Indicates to the targeted element which action to take..
//
// Value: "toggle-popover"; "show-popover"; "hide-popover"; "close"; "request-close"; "show-modal"; a custom command keyword.
func Command(value string) types.Command {
	return types.Command{IAttribute: attrs.Command(value)}
}

// Commandfor
//
// Element(s): button.
//
// Description: Targets another element to be invoked..
//
// Value: ID*.
func Commandfor(value string) types.Commandfor {
	return types.Commandfor{IAttribute: attrs.Commandfor(value)}
}

// Content
//
// Element(s): meta.
//
// Description: Value of the element.
//
// Value: Text*.
func Content(value string) types.Content {
	return types.Content{IAttribute: attrs.Content(value)}
}

// Contenteditable
//
// Element(s): HTML elements.
//
// Description: Whether the element is editable.
//
// Value: "true"; "plaintext-only"; "false".
func Contenteditable(value string) types.Contenteditable {
	return types.Contenteditable{IAttribute: attrs.Contenteditable(value)}
}

// Controls
//
// Element(s): audio; video.
//
// Description: Show user agent controls.
//
// Value: Boolean attribute.
func Controls(value bool) types.Controls {
	return types.Controls{IAttribute: attrs.Controls(value)}
}

// Coords
//
// Element(s): area.
//
// Description: Coordinates for the shape to be created in an image map.
//
// Value: Valid list of floating-point numbers*.
func Coords(value string) types.Coords {
	return types.Coords{IAttribute: attrs.Coords(value)}
}

// Crossorigin
//
// Element(s): audio; img; link; script; video.
//
// Description: How the element handles crossorigin requests.
//
// Value: "anonymous"; "use-credentials".
func Crossorigin(value string) types.Crossorigin {
	return types.Crossorigin{IAttribute: attrs.Crossorigin(value)}
}

// Data
//
// Element(s): object.
//
// Description: Address of the resource.
//
// Value: Valid non-empty URL potentially surrounded by spaces.
func Data(value string) types.Data {
	return types.Data{IAttribute: attrs.Data(value)}
}

// Datetime
//
// Element(s): del; ins.
//
// Description: Date and (optionally) time of the change.
//
// Value: Valid date string with optional time.
//
// Element(s): time.
//
// Description: Machine-readable value.
//
// Value: Valid month string, valid date string, valid yearless date string, valid time string, valid local date and time string, valid time-zone offset string, valid global date and time string, valid week string, valid non-negative integer, or valid duration string.
func Datetime(value string) types.Datetime {
	return types.Datetime{IAttribute: attrs.Datetime(value)}
}

// Decoding
//
// Element(s): img.
//
// Description: Decoding hint to use when processing this image for presentation.
//
// Value: "sync"; "async"; "auto".
func Decoding(value string) types.Decoding {
	return types.Decoding{IAttribute: attrs.Decoding(value)}
}

// Default
//
// Element(s): track.
//
// Description: Enable the track if no other text track is more suitable.
//
// Value: Boolean attribute.
func Default(value bool) types.Default {
	return types.Default{IAttribute: attrs.Default(value)}
}

// Defer
//
// Element(s): script.
//
// Description: Defer script execution.
//
// Value: Boolean attribute.
func Defer(value bool) types.Defer {
	return types.Defer{IAttribute: attrs.Defer(value)}
}

// Dir
//
// Element(s): HTML elements.
//
// Description: The text directionality of the element.
//
// Value: "ltr"; "rtl"; "auto".
//
// Element(s): bdo.
//
// Description: The text directionality of the element.
//
// Value: "ltr"; "rtl".
func Dir(value string) types.Dir {
	return types.Dir{IAttribute: attrs.Dir(value)}
}

// Dirname
//
// Element(s): input; textarea.
//
// Description: Name of form control to use for sending the element's directionality in form submission.
//
// Value: Text*.
func Dirname(value string) types.Dirname {
	return types.Dirname{IAttribute: attrs.Dirname(value)}
}

// Disabled
//
// Element(s): button; input; optgroup; option; select; textarea; form-associated custom elements.
//
// Description: Whether the form control is disabled.
//
// Value: Boolean attribute.
//
// Element(s): fieldset.
//
// Description: Whether the descendant form controls, except any inside legend, are disabled.
//
// Value: Boolean attribute.
//
// Element(s): link.
//
// Description: Whether the link is disabled.
//
// Value: Boolean attribute.
func Disabled(value bool) types.Disabled {
	return types.Disabled{IAttribute: attrs.Disabled(value)}
}

// Download
//
// Element(s): a; area.
//
// Description: Whether to download the resource instead of navigating to it, and its filename if so.
//
// Value: Text.
func Download(value string) types.Download {
	return types.Download{IAttribute: attrs.Download(value)}
}

// Draggable
//
// Element(s): HTML elements.
//
// Description: Whether the element is draggable.
//
// Value: "true"; "false".
func Draggable(value string) types.Draggable {
	return types.Draggable{IAttribute: attrs.Draggable(value)}
}

// Enctype
//
// Element(s): form.
//
// Description: Entry list encoding type to use for form submission.
//
// Value: "application/x-www-form-urlencoded"; "multipart/form-data"; "text/plain".
func Enctype(value string) types.Enctype {
	return types.Enctype{IAttribute: attrs.Enctype(value)}
}

// Enterkeyhint
//
// Element(s): HTML elements.
//
// Description: Hint for selecting an enter key action.
//
// Value: "enter"; "done"; "go"; "next"; "previous"; "search"; "send".
func Enterkeyhint(value string) types.Enterkeyhint {
	return types.Enterkeyhint{IAttribute: attrs.Enterkeyhint(value)}
}

// Fetchpriority
//
// Element(s): img; link; script.
//
// Description: Sets the priority for fetches initiated by the element.
//
// Value: "auto"; "high"; "low".
func Fetchpriority(value string) types.Fetchpriority {
	return types.Fetchpriority{IAttribute: attrs.Fetchpriority(value)}
}

// For
//
// Element(s): label.
//
// Description: Associate the label with form control.
//
// Value: ID*.
//
// Element(s): output.
//
// Description: Specifies controls from which the output was calculated.
//
// Value: Unordered set of unique space-separated tokens consisting of IDs*.
func For(value string) types.For {
	return types.For{IAttribute: attrs.For(value)}
}

// Form
//
// Element(s): button; fieldset; input; object; output; select; textarea; form-associated custom elements.
//
// Description: Associates the element with a form element.
//
// Value: ID*.
func Form(value string) types.Form {
	return types.Form{IAttribute: attrs.Form(value)}
}

// Formaction
//
// Element(s): button; input.
//
// Description: URL to use for form submission.
//
// Value: Valid non-empty URL potentially surrounded by spaces.
func Formaction(value string) types.Formaction {
	return types.Formaction{IAttribute: attrs.Formaction(value)}
}

// Formenctype
//
// Element(s): button; input.
//
// Description: Entry list encoding type to use for form submission.
//
// Value: "application/x-www-form-urlencoded"; "multipart/form-data"; "text/plain".
func Formenctype(value string) types.Formenctype {
	return types.Formenctype{IAttribute: attrs.Formenctype(value)}
}

// Formmethod
//
// Element(s): button; input.
//
// Description: Variant to use for form submission.
//
// Value: "GET"; "POST"; "dialog".
func Formmethod(value string) types.Formmethod {
	return types.Formmethod{IAttribute: attrs.Formmethod(value)}
}

// Formnovalidate
//
// Element(s): button; input.
//
// Description: Bypass form control validation for form submission.
//
// Value: Boolean attribute.
func Formnovalidate(value bool) types.Formnovalidate {
	return types.Formnovalidate{IAttribute: attrs.Formnovalidate(value)}
}

// Formtarget
//
// Element(s): button; input.
//
// Description: Navigable for form submission.
//
// Value: Valid navigable target name or keyword.
func Formtarget(value string) types.Formtarget {
	return types.Formtarget{IAttribute: attrs.Formtarget(value)}
}

// Headers
//
// Element(s): td; th.
//
// Description: The header cells for this cell.
//
// Value: Unordered set of unique space-separated tokens consisting of IDs*.
func Headers(value string) types.Headers {
	return types.Headers{IAttribute: attrs.Headers(value)}
}

// Height
//
// Element(s): canvas; embed; iframe; img; input; object; source (in picture); video.
//
// Description: Vertical dimension.
//
// Value: Valid non-negative integer.
func Height(value string) types.Height {
	return types.Height{IAttribute: attrs.Height(value)}
}

// Hidden
//
// Element(s): HTML elements.
//
// Description: Whether the element is relevant.
//
// Value: "until-found"; "hidden"; the empty string.
func Hidden(value string) types.Hidden {
	return types.Hidden{IAttribute: attrs.Hidden(value)}
}

// High
//
// Element(s): meter.
//
// Description: Low limit of high range.
//
// Value: Valid floating-point number*.
func High(value string) types.High {
	return types.High{IAttribute: attrs.High(value)}
}

// Href
//
// Element(s): a; area.
//
// Description: Address of the hyperlink.
//
// Value: Valid URL potentially surrounded by spaces.
//
// Element(s): link.
//
// Description: Address of the hyperlink.
//
// Value: Valid non-empty URL potentially surrounded by spaces.
//
// Element(s): base.
//
// Description: Document base URL.
//
// Value: Valid URL potentially surrounded by spaces.
func Href(value string) types.Href {
	return types.Href{IAttribute: attrs.Href(value)}
}

// Hreflang
//
// Element(s): a; link.
//
// Description: Language of the linked resource.
//
// Value: Valid BCP 47 language tag.
func Hreflang(value string) types.Hreflang {
	return types.Hreflang{IAttribute: attrs.Hreflang(value)}
}

// HttpEquiv
//
// Element(s): meta.
//
// Description: Pragma directive.
//
// Value: "content-type"; "default-style"; "refresh"; "x-ua-compatible"; "content-security-policy".
func HttpEquiv(value string) types.HttpEquiv {
	return types.HttpEquiv{IAttribute: attrs.HttpEquiv(value)}
}

// Id
//
// Element(s): HTML elements.
//
// Description: The element's ID.
//
// Value: Text*.
func Id(value string) types.Id {
	return types.Id{IAttribute: attrs.Id(value)}
}

// Imagesizes
//
// Element(s): link.
//
// Description: Image sizes for different page layouts (for rel="preload").
//
// Value: Valid source size list.
func Imagesizes(value string) types.Imagesizes {
	return types.Imagesizes{IAttribute: attrs.Imagesizes(value)}
}

// Imagesrcset
//
// Element(s): link.
//
// Description: Images to use in different situations, e.g., high-resolution displays, small monitors, etc. (for rel="preload").
//
// Value: Comma-separated list of image candidate strings.
func Imagesrcset(value string) types.Imagesrcset {
	return types.Imagesrcset{IAttribute: attrs.Imagesrcset(value)}
}

// Inert
//
// Element(s): HTML elements.
//
// Description: Whether the element is inert..
//
// Value: Boolean attribute.
func Inert(value bool) types.Inert {
	return types.Inert{IAttribute: attrs.Inert(value)}
}

// Inputmode
//
// Element(s): HTML elements.
//
// Description: Hint for selecting an input modality.
//
// Value: "none"; "text"; "tel"; "email"; "url"; "numeric"; "decimal"; "search".
func Inputmode(value string) types.Inputmode {
	return types.Inputmode{IAttribute: attrs.Inputmode(value)}
}

// Integrity
//
// Element(s): link; script.
//
// Description: Integrity metadata used in Subresource Integrity checks [SRI].
//
// Value: Text.
func Integrity(value string) types.Integrity {
	return types.Integrity{IAttribute: attrs.Integrity(value)}
}

// Is
//
// Element(s): HTML elements.
//
// Description: Creates a customized built-in element.
//
// Value: Valid custom element name of a defined customized built-in element.
func Is(value string) types.Is {
	return types.Is{IAttribute: attrs.Is(value)}
}

// Ismap
//
// Element(s): img.
//
// Description: Whether the image is a server-side image map.
//
// Value: Boolean attribute.
func Ismap(value bool) types.Ismap {
	return types.Ismap{IAttribute: attrs.Ismap(value)}
}

// Itemid
//
// Element(s): HTML elements.
//
// Description: Global identifier for a microdata item.
//
// Value: Valid URL potentially surrounded by spaces.
func Itemid(value string) types.Itemid {
	return types.Itemid{IAttribute: attrs.Itemid(value)}
}

// Itemprop
//
// Element(s): HTML elements.
//
// Description: Property names of a microdata item.
//
// Value: Unordered set of unique space-separated tokens consisting of valid absolute URLs, defined property names, or text*.
func Itemprop(value string) types.Itemprop {
	return types.Itemprop{IAttribute: attrs.Itemprop(value)}
}

// Itemref
//
// Element(s): HTML elements.
//
// Description: Referenced elements.
//
// Value: Unordered set of unique space-separated tokens consisting of IDs*.
func Itemref(value string) types.Itemref {
	return types.Itemref{IAttribute: attrs.Itemref(value)}
}

// Itemscope
//
// Element(s): HTML elements.
//
// Description: Introduces a microdata item.
//
// Value: Boolean attribute.
func Itemscope(value bool) types.Itemscope {
	return types.Itemscope{IAttribute: attrs.Itemscope(value)}
}

// Itemtype
//
// Element(s): HTML elements.
//
// Description: Item types of a microdata item.
//
// Value: Unordered set of unique space-separated tokens consisting of valid absolute URLs*.
func Itemtype(value string) types.Itemtype {
	return types.Itemtype{IAttribute: attrs.Itemtype(value)}
}

// Kind
//
// Element(s): track.
//
// Description: The type of text track.
//
// Value: "subtitles"; "captions"; "descriptions"; "chapters"; "metadata".
func Kind(value string) types.Kind {
	return types.Kind{IAttribute: attrs.Kind(value)}
}

// Label
//
// Element(s): optgroup; option; track.
//
// Description: User-visible label.
//
// Value: Text.
func Label(value string) types.Label {
	return types.Label{IAttribute: attrs.Label(value)}
}

// Lang
//
// Element(s): HTML elements.
//
// Description: Language of the element.
//
// Value: Valid BCP 47 language tag or the empty string.
func Lang(value string) types.Lang {
	return types.Lang{IAttribute: attrs.Lang(value)}
}

// List
//
// Element(s): input.
//
// Description: List of autocomplete options.
//
// Value: ID*.
func List(value string) types.List {
	return types.List{IAttribute: attrs.List(value)}
}

// Loading
//
// Element(s): iframe; img.
//
// Description: Used when determining loading deferral.
//
// Value: "lazy"; "eager".
func Loading(value string) types.Loading {
	return types.Loading{IAttribute: attrs.Loading(value)}
}

// Loop
//
// Element(s): audio; video.
//
// Description: Whether to loop the media resource.
//
// Value: Boolean attribute.
func Loop(value bool) types.Loop {
	return types.Loop{IAttribute: attrs.Loop(value)}
}

// Low
//
// Element(s): meter.
//
// Description: High limit of low range.
//
// Value: Valid floating-point number*.
func Low(value string) types.Low {
	return types.Low{IAttribute: attrs.Low(value)}
}

// Max
//
// Element(s): input.
//
// Description: Maximum value.
//
// Value: Varies*.
//
// Element(s): meter; progress.
//
// Description: Upper bound of range.
//
// Value: Valid floating-point number*.
func Max(value string) types.Max {
	return types.Max{IAttribute: attrs.Max(value)}
}

// Maxlength
//
// Element(s): input; textarea.
//
// Description: Maximum length of value.
//
// Value: Valid non-negative integer.
func Maxlength(value string) types.Maxlength {
	return types.Maxlength{IAttribute: attrs.Maxlength(value)}
}

// Media
//
// Element(s): link; meta; source; style.
//
// Description: Applicable media.
//
// Value: Valid media query list.
func Media(value string) types.Media {
	return types.Media{IAttribute: attrs.Media(value)}
}

// Method
//
// Element(s): form.
//
// Description: Variant to use for form submission.
//
// Value: "GET"; "POST"; "dialog".
func Method(value string) types.Method {
	return types.Method{IAttribute: attrs.Method(value)}
}

// Min
//
// Element(s): input.
//
// Description: Minimum value.
//
// Value: Varies*.
//
// Element(s): meter.
//
// Description: Lower bound of range.
//
// Value: Valid floating-point number*.
func Min(value string) types.Min {
	return types.Min{IAttribute: attrs.Min(value)}
}

// Minlength
//
// Element(s): input; textarea.
//
// Description: Minimum length of value.
//
// Value: Valid non-negative integer.
func Minlength(value string) types.Minlength {
	return types.Minlength{IAttribute: attrs.Minlength(value)}
}

// Multiple
//
// Element(s): input; select.
//
// Description: Whether to allow multiple values.
//
// Value: Boolean attribute.
func Multiple(value bool) types.Multiple {
	return types.Multiple{IAttribute: attrs.Multiple(value)}
}

// Muted
//
// Element(s): audio; video.
//
// Description: Whether to mute the media resource by default.
//
// Value: Boolean attribute.
func Muted(value bool) types.Muted {
	return types.Muted{IAttribute: attrs.Muted(value)}
}

// Name
//
// Element(s): button; fieldset; input; output; select; textarea; form-associated custom elements.
//
// Description: Name of the element to use for form submission and in the form.elements API.
//
// Value: Text*.
//
// Element(s): details.
//
// Description: Name of group of mutually-exclusive details elements.
//
// Value: Text*.
//
// Element(s): form.
//
// Description: Name of form to use in the document.forms API.
//
// Value: Text*.
//
// Element(s): iframe; object.
//
// Description: Name of content navigable.
//
// Value: Valid navigable target name or keyword.
//
// Element(s): map.
//
// Description: Name of image map to reference from the usemap attribute.
//
// Value: Text*.
//
// Element(s): meta.
//
// Description: Metadata name.
//
// Value: Text*.
//
// Element(s): slot.
//
// Description: Name of shadow tree slot.
//
// Value: Text.
func Name(value string) types.Name {
	return types.Name{IAttribute: attrs.Name(value)}
}

// Nomodule
//
// Element(s): script.
//
// Description: Prevents execution in user agents that support module scripts.
//
// Value: Boolean attribute.
func Nomodule(value bool) types.Nomodule {
	return types.Nomodule{IAttribute: attrs.Nomodule(value)}
}

// Nonce
//
// Element(s): HTML elements.
//
// Description: Cryptographic nonce used in Content Security Policy checks [CSP].
//
// Value: Text.
func Nonce(value string) types.Nonce {
	return types.Nonce{IAttribute: attrs.Nonce(value)}
}

// Novalidate
//
// Element(s): form.
//
// Description: Bypass form control validation for form submission.
//
// Value: Boolean attribute.
func Novalidate(value bool) types.Novalidate {
	return types.Novalidate{IAttribute: attrs.Novalidate(value)}
}

// Open
//
// Element(s): details.
//
// Description: Whether the details are visible.
//
// Value: Boolean attribute.
//
// Element(s): dialog.
//
// Description: Whether the dialog box is showing.
//
// Value: Boolean attribute.
func Open(value bool) types.Open {
	return types.Open{IAttribute: attrs.Open(value)}
}

// Optimum
//
// Element(s): meter.
//
// Description: Optimum value in gauge.
//
// Value: Valid floating-point number*.
func Optimum(value string) types.Optimum {
	return types.Optimum{IAttribute: attrs.Optimum(value)}
}

// Pattern
//
// Element(s): input.
//
// Description: Pattern to be matched by the form control's value.
//
// Value: Regular expression matching the JavaScript Pattern production.
func Pattern(value string) types.Pattern {
	return types.Pattern{IAttribute: attrs.Pattern(value)}
}

// Ping
//
// Element(s): a; area.
//
// Description: URLs to ping.
//
// Value: Set of space-separated tokens consisting of valid non-empty URLs.
func Ping(value string) types.Ping {
	return types.Ping{IAttribute: attrs.Ping(value)}
}

// Placeholder
//
// Element(s): input; textarea.
//
// Description: User-visible label to be placed within the form control.
//
// Value: Text*.
func Placeholder(value string) types.Placeholder {
	return types.Placeholder{IAttribute: attrs.Placeholder(value)}
}

// Playsinline
//
// Element(s): video.
//
// Description: Encourage the user agent to display video content within the element's playback area.
//
// Value: Boolean attribute.
func Playsinline(value bool) types.Playsinline {
	return types.Playsinline{IAttribute: attrs.Playsinline(value)}
}

// Popover
//
// Element(s): HTML elements.
//
// Description: Makes the element a popover element.
//
// Value: "auto"; "manual"; "hint".
func Popover(value string) types.Popover {
	return types.Popover{IAttribute: attrs.Popover(value)}
}

// Popovertarget
//
// Element(s): button; input.
//
// Description: Targets a popover element to toggle, show, or hide.
//
// Value: ID*.
func Popovertarget(value string) types.Popovertarget {
	return types.Popovertarget{IAttribute: attrs.Popovertarget(value)}
}

// Popovertargetaction
//
// Element(s): button; input.
//
// Description: Indicates whether a targeted popover element is to be toggled, shown, or hidden.
//
// Value: "toggle"; "show"; "hide".
func Popovertargetaction(value string) types.Popovertargetaction {
	return types.Popovertargetaction{IAttribute: attrs.Popovertargetaction(value)}
}

// Poster
//
// Element(s): video.
//
// Description: Poster frame to show prior to video playback.
//
// Value: Valid non-empty URL potentially surrounded by spaces.
func Poster(value string) types.Poster {
	return types.Poster{IAttribute: attrs.Poster(value)}
}

// Preload
//
// Element(s): audio; video.
//
// Description: Hints how much buffering the media resource will likely need.
//
// Value: "none"; "metadata"; "auto".
func Preload(value string) types.Preload {
	return types.Preload{IAttribute: attrs.Preload(value)}
}

// Readonly
//
// Element(s): input; textarea.
//
// Description: Whether to allow the value to be edited by the user.
//
// Value: Boolean attribute.
//
// Element(s): form-associated custom elements.
//
// Description: Affects willValidate, plus any behavior added by the custom element author.
//
// Value: Boolean attribute.
func Readonly(value bool) types.Readonly {
	return types.Readonly{IAttribute: attrs.Readonly(value)}
}

// Referrerpolicy
//
// Element(s): a; area; iframe; img; link; script.
//
// Description: Referrer policy for fetches initiated by the element.
//
// Value: Referrer policy.
func Referrerpolicy(value string) types.Referrerpolicy {
	return types.Referrerpolicy{IAttribute: attrs.Referrerpolicy(value)}
}

// Rel
//
// Element(s): a; area.
//
// Description: Relationship between the location in the document containing the hyperlink and the destination resource.
//
// Value: Unordered set of unique space-separated tokens*.
//
// Element(s): link.
//
// Description: Relationship between the document containing the hyperlink and the destination resource.
//
// Value: Unordered set of unique space-separated tokens*.
func Rel(value string) types.Rel {
	return types.Rel{IAttribute: attrs.Rel(value)}
}

// Required
//
// Element(s): input; select; textarea.
//
// Description: Whether the control is required for form submission.
//
// Value: Boolean attribute.
func Required(value bool) types.Required {
	return types.Required{IAttribute: attrs.Required(value)}
}

// Reversed
//
// Element(s): ol.
//
// Description: Number the list backwards.
//
// Value: Boolean attribute.
func Reversed(value bool) types.Reversed {
	return types.Reversed{IAttribute: attrs.Reversed(value)}
}

// Rows
//
// Element(s): textarea.
//
// Description: Number of lines to show.
//
// Value: Valid non-negative integer greater than zero.
func Rows(value string) types.Rows {
	return types.Rows{IAttribute: attrs.Rows(value)}
}

// Rowspan
//
// Element(s): td; th.
//
// Description: Number of rows that the cell is to span.
//
// Value: Valid non-negative integer.
func Rowspan(value string) types.Rowspan {
	return types.Rowspan{IAttribute: attrs.Rowspan(value)}
}

// Sandbox
//
// Element(s): iframe.
//
// Description: Security rules for nested content.
//
// Value: Unordered set of unique space-separated tokens, ASCII case-insensitive, consisting of "allow-downloads""allow-forms""allow-modals""allow-orientation-lock""allow-pointer-lock""allow-popups""allow-popups-to-escape-sandbox""allow-presentation""allow-same-origin""allow-scripts""allow-top-navigation""allow-top-navigation-by-user-activation""allow-top-navigation-to-custom-protocols".
func Sandbox(value string) types.Sandbox {
	return types.Sandbox{IAttribute: attrs.Sandbox(value)}
}

// Scope
//
// Element(s): th.
//
// Description: Specifies which cells the header cell applies to.
//
// Value: "row"; "col"; "rowgroup"; "colgroup".
func Scope(value string) types.Scope {
	return types.Scope{IAttribute: attrs.Scope(value)}
}

// Selected
//
// Element(s): option.
//
// Description: Whether the option is selected by default.
//
// Value: Boolean attribute.
func Selected(value bool) types.Selected {
	return types.Selected{IAttribute: attrs.Selected(value)}
}

// Shadowrootclonable
//
// Element(s): template.
//
// Description: Sets clonable on a declarative shadow root.
//
// Value: Boolean attribute.
func Shadowrootclonable(value bool) types.Shadowrootclonable {
	return types.Shadowrootclonable{IAttribute: attrs.Shadowrootclonable(value)}
}

// Shadowrootcustomelementregistry
//
// Element(s): template.
//
// Description: Enables declarative shadow roots to indicate they will use a custom element registry.
//
// Value: Boolean attribute.
func Shadowrootcustomelementregistry(value bool) types.Shadowrootcustomelementregistry {
	return types.Shadowrootcustomelementregistry{IAttribute: attrs.Shadowrootcustomelementregistry(value)}
}

// Shadowrootdelegatesfocus
//
// Element(s): template.
//
// Description: Sets delegates focus on a declarative shadow root.
//
// Value: Boolean attribute.
func Shadowrootdelegatesfocus(value bool) types.Shadowrootdelegatesfocus {
	return types.Shadowrootdelegatesfocus{IAttribute: attrs.Shadowrootdelegatesfocus(value)}
}

// Shadowrootmode
//
// Element(s): template.
//
// Description: Enables streaming declarative shadow roots.
//
// Value: "open"; "closed".
func Shadowrootmode(value string) types.Shadowrootmode {
	return types.Shadowrootmode{IAttribute: attrs.Shadowrootmode(value)}
}

// Shadowrootserializable
//
// Element(s): template.
//
// Description: Sets serializable on a declarative shadow root.
//
// Value: Boolean attribute.
func Shadowrootserializable(value bool) types.Shadowrootserializable {
	return types.Shadowrootserializable{IAttribute: attrs.Shadowrootserializable(value)}
}

// Shape
//
// Element(s): area.
//
// Description: The kind of shape to be created in an image map.
//
// Value: "circle"; "default"; "poly"; "rect".
func Shape(value string) types.Shape {
	return types.Shape{IAttribute: attrs.Shape(value)}
}

// Size
//
// Element(s): input; select.
//
// Description: Size of the control.
//
// Value: Valid non-negative integer greater than zero.
func Size(value string) types.Size {
	return types.Size{IAttribute: attrs.Size(value)}
}

// Sizes
//
// Element(s): link.
//
// Description: Sizes of the icons (for rel="icon").
//
// Value: Unordered set of unique space-separated tokens, ASCII case-insensitive, consisting of sizes*.
//
// Element(s): img; source.
//
// Description: Image sizes for different page layouts.
//
// Value: Valid source size list.
func Sizes(value string) types.Sizes {
	return types.Sizes{IAttribute: attrs.Sizes(value)}
}

// Slot
//
// Element(s): HTML elements.
//
// Description: The element's desired slot.
//
// Value: Text.
func Slot(value string) types.Slot {
	return types.Slot{IAttribute: attrs.Slot(value)}
}

// Span
//
// Element(s): col; colgroup.
//
// Description: Number of columns spanned by the element.
//
// Value: Valid non-negative integer greater than zero.
func Span(value string) types.Span {
	return types.Span{IAttribute: attrs.Span(value)}
}

// Spellcheck
//
// Element(s): HTML elements.
//
// Description: Whether the element is to have its spelling and grammar checked.
//
// Value: "true"; "false"; the empty string.
func Spellcheck(value string) types.Spellcheck {
	return types.Spellcheck{IAttribute: attrs.Spellcheck(value)}
}

// Src
//
// Element(s): audio; embed; iframe; img; input; script; source (in video or audio); track; video.
//
// Description: Address of the resource.
//
// Value: Valid non-empty URL potentially surrounded by spaces.
func Src(value string) types.Src {
	return types.Src{IAttribute: attrs.Src(value)}
}

// Srcdoc
//
// Element(s): iframe.
//
// Description: A document to render in the iframe.
//
// Value: The source of an iframe srcdoc document*.
func Srcdoc(value string) types.Srcdoc {
	return types.Srcdoc{IAttribute: attrs.Srcdoc(value)}
}

// Srclang
//
// Element(s): track.
//
// Description: Language of the text track.
//
// Value: Valid BCP 47 language tag.
func Srclang(value string) types.Srclang {
	return types.Srclang{IAttribute: attrs.Srclang(value)}
}

// Srcset
//
// Element(s): img; source.
//
// Description: Images to use in different situations, e.g., high-resolution displays, small monitors, etc..
//
// Value: Comma-separated list of image candidate strings.
func Srcset(value string) types.Srcset {
	return types.Srcset{IAttribute: attrs.Srcset(value)}
}

// Start
//
// Element(s): ol.
//
// Description: Starting value of the list.
//
// Value: Valid integer.
func Start(value string) types.Start {
	return types.Start{IAttribute: attrs.Start(value)}
}

// Step
//
// Element(s): input.
//
// Description: Granularity to be matched by the form control's value.
//
// Value: Valid floating-point number greater than zero, or "any".
func Step(value string) types.Step {
	return types.Step{IAttribute: attrs.Step(value)}
}

// Style
//
// Element(s): HTML elements.
//
// Description: Presentational and formatting instructions.
//
// Value: CSS declarations*.
func Style(value string) types.Style {
	return types.Style{IAttribute: attrs.Style(value)}
}

// Tabindex
//
// Element(s): HTML elements.
//
// Description: Whether the element is focusable and sequentially focusable, and the relative order of the element for the purposes of sequential focus navigation.
//
// Value: Valid integer.
func Tabindex(value string) types.Tabindex {
	return types.Tabindex{IAttribute: attrs.Tabindex(value)}
}

// Target
//
// Element(s): a; area.
//
// Description: Navigable for hyperlink navigation.
//
// Value: Valid navigable target name or keyword.
//
// Element(s): base.
//
// Description: Default navigable for hyperlink navigation and form submission.
//
// Value: Valid navigable target name or keyword.
//
// Element(s): form.
//
// Description: Navigable for form submission.
//
// Value: Valid navigable target name or keyword.
func Target(value string) types.Target {
	return types.Target{IAttribute: attrs.Target(value)}
}

// Title
//
// Element(s): HTML elements.
//
// Description: Advisory information for the element.
//
// Value: Text.
//
// Element(s): abbr; dfn.
//
// Description: Full term or expansion of abbreviation.
//
// Value: Text.
//
// Element(s): input.
//
// Description: Description of pattern (when used with pattern attribute).
//
// Value: Text.
//
// Element(s): link.
//
// Description: Title of the link.
//
// Value: Text.
//
// Element(s): link; style.
//
// Description: CSS style sheet set name.
//
// Value: Text.
func Title(value string) types.Title {
	return types.Title{IAttribute: attrs.Title(value)}
}

// Translate
//
// Element(s): HTML elements.
//
// Description: Whether the element is to be translated when the page is localized.
//
// Value: "yes"; "no".
func Translate(value string) types.Translate {
	return types.Translate{IAttribute: attrs.Translate(value)}
}

// Type
//
// Element(s): a; link.
//
// Description: Hint for the type of the referenced resource.
//
// Value: Valid MIME type string.
//
// Element(s): button.
//
// Description: Type of button.
//
// Value: "submit"; "reset"; "button".
//
// Element(s): embed; object; source.
//
// Description: Type of embedded resource.
//
// Value: Valid MIME type string.
//
// Element(s): input.
//
// Description: Type of form control.
//
// Value: input type keyword.
//
// Element(s): ol.
//
// Description: Kind of list marker.
//
// Value: "1"; "a"; "A"; "i"; "I".
//
// Element(s): script.
//
// Description: Type of script.
//
// Value: "module"; a valid MIME type string that is not a JavaScript MIME type essence match.
func Type(value string) types.Type {
	return types.Type{IAttribute: attrs.Type(value)}
}

// Usemap
//
// Element(s): img.
//
// Description: Name of image map to use.
//
// Value: Valid hash-name reference*.
func Usemap(value string) types.Usemap {
	return types.Usemap{IAttribute: attrs.Usemap(value)}
}

// Value
//
// Element(s): button; option.
//
// Description: Value to be used for form submission.
//
// Value: Text.
//
// Element(s): data.
//
// Description: Machine-readable value.
//
// Value: Text*.
//
// Element(s): input.
//
// Description: Value of the form control.
//
// Value: Varies*.
//
// Element(s): li.
//
// Description: Ordinal value of the list item.
//
// Value: Valid integer.
//
// Element(s): meter; progress.
//
// Description: Current value of the element.
//
// Value: Valid floating-point number.
func Value(value string) types.Value {
	return types.Value{IAttribute: attrs.Value(value)}
}

// Width
//
// Element(s): canvas; embed; iframe; img; input; object; source (in picture); video.
//
// Description: Horizontal dimension.
//
// Value: Valid non-negative integer.
func Width(value string) types.Width {
	return types.Width{IAttribute: attrs.Width(value)}
}

// Wrap
//
// Element(s): textarea.
//
// Description: How the value of the form control is to be wrapped for form submission.
//
// Value: "soft"; "hard".
func Wrap(value string) types.Wrap {
	return types.Wrap{IAttribute: attrs.Wrap(value)}
}

// Writingsuggestions
//
// Element(s): HTML elements.
//
// Description: Whether the element can offer writing suggestions or not..
//
// Value: "true"; "false"; the empty string.
func Writingsuggestions(value string) types.Writingsuggestions {
	return types.Writingsuggestions{IAttribute: attrs.Writingsuggestions(value)}
}

// Onafterprint
//
// Element(s): body.
//
// Description: afterprint event handler for Window object.
//
// Value: Event handler content attribute.
func Onafterprint(value string) types.Onafterprint {
	return types.Onafterprint{IAttribute: attrs.Onafterprint(value)}
}

// Onauxclick
//
// Element(s): HTML elements.
//
// Description: auxclick event handler.
//
// Value: Event handler content attribute.
func Onauxclick(value string) types.Onauxclick {
	return types.Onauxclick{IAttribute: attrs.Onauxclick(value)}
}

// Onbeforeinput
//
// Element(s): HTML elements.
//
// Description: beforeinput event handler.
//
// Value: Event handler content attribute.
func Onbeforeinput(value string) types.Onbeforeinput {
	return types.Onbeforeinput{IAttribute: attrs.Onbeforeinput(value)}
}

// Onbeforematch
//
// Element(s): HTML elements.
//
// Description: beforematch event handler.
//
// Value: Event handler content attribute.
func Onbeforematch(value string) types.Onbeforematch {
	return types.Onbeforematch{IAttribute: attrs.Onbeforematch(value)}
}

// Onbeforeprint
//
// Element(s): body.
//
// Description: beforeprint event handler for Window object.
//
// Value: Event handler content attribute.
func Onbeforeprint(value string) types.Onbeforeprint {
	return types.Onbeforeprint{IAttribute: attrs.Onbeforeprint(value)}
}

// Onbeforeunload
//
// Element(s): body.
//
// Description: beforeunload event handler for Window object.
//
// Value: Event handler content attribute.
func Onbeforeunload(value string) types.Onbeforeunload {
	return types.Onbeforeunload{IAttribute: attrs.Onbeforeunload(value)}
}

// Onbeforetoggle
//
// Element(s): HTML elements.
//
// Description: beforetoggle event handler.
//
// Value: Event handler content attribute.
func Onbeforetoggle(value string) types.Onbeforetoggle {
	return types.Onbeforetoggle{IAttribute: attrs.Onbeforetoggle(value)}
}

// Onblur
//
// Element(s): HTML elements.
//
// Description: blur event handler.
//
// Value: Event handler content attribute.
func Onblur(value string) types.Onblur {
	return types.Onblur{IAttribute: attrs.Onblur(value)}
}

// Oncancel
//
// Element(s): HTML elements.
//
// Description: cancel event handler.
//
// Value: Event handler content attribute.
func Oncancel(value string) types.Oncancel {
	return types.Oncancel{IAttribute: attrs.Oncancel(value)}
}

// Oncanplay
//
// Element(s): HTML elements.
//
// Description: canplay event handler.
//
// Value: Event handler content attribute.
func Oncanplay(value string) types.Oncanplay {
	return types.Oncanplay{IAttribute: attrs.Oncanplay(value)}
}

// Oncanplaythrough
//
// Element(s): HTML elements.
//
// Description: canplaythrough event handler.
//
// Value: Event handler content attribute.
func Oncanplaythrough(value string) types.Oncanplaythrough {
	return types.Oncanplaythrough{IAttribute: attrs.Oncanplaythrough(value)}
}

// Onchange
//
// Element(s): HTML elements.
//
// Description: change event handler.
//
// Value: Event handler content attribute.
func Onchange(value string) types.Onchange {
	return types.Onchange{IAttribute: attrs.Onchange(value)}
}

// Onclick
//
// Element(s): HTML elements.
//
// Description: click event handler.
//
// Value: Event handler content attribute.
func Onclick(value string) types.Onclick {
	return types.Onclick{IAttribute: attrs.Onclick(value)}
}

// Onclose
//
// Element(s): HTML elements.
//
// Description: close event handler.
//
// Value: Event handler content attribute.
func Onclose(value string) types.Onclose {
	return types.Onclose{IAttribute: attrs.Onclose(value)}
}

// Oncommand
//
// Element(s): HTML elements.
//
// Description: command event handler.
//
// Value: Event handler content attribute.
func Oncommand(value string) types.Oncommand {
	return types.Oncommand{IAttribute: attrs.Oncommand(value)}
}

// Oncontextlost
//
// Element(s): HTML elements.
//
// Description: contextlost event handler.
//
// Value: Event handler content attribute.
func Oncontextlost(value string) types.Oncontextlost {
	return types.Oncontextlost{IAttribute: attrs.Oncontextlost(value)}
}

// Oncontextmenu
//
// Element(s): HTML elements.
//
// Description: contextmenu event handler.
//
// Value: Event handler content attribute.
func Oncontextmenu(value string) types.Oncontextmenu {
	return types.Oncontextmenu{IAttribute: attrs.Oncontextmenu(value)}
}

// Oncontextrestored
//
// Element(s): HTML elements.
//
// Description: contextrestored event handler.
//
// Value: Event handler content attribute.
func Oncontextrestored(value string) types.Oncontextrestored {
	return types.Oncontextrestored{IAttribute: attrs.Oncontextrestored(value)}
}

// Oncopy
//
// Element(s): HTML elements.
//
// Description: copy event handler.
//
// Value: Event handler content attribute.
func Oncopy(value string) types.Oncopy {
	return types.Oncopy{IAttribute: attrs.Oncopy(value)}
}

// Oncuechange
//
// Element(s): HTML elements.
//
// Description: cuechange event handler.
//
// Value: Event handler content attribute.
func Oncuechange(value string) types.Oncuechange {
	return types.Oncuechange{IAttribute: attrs.Oncuechange(value)}
}

// Oncut
//
// Element(s): HTML elements.
//
// Description: cut event handler.
//
// Value: Event handler content attribute.
func Oncut(value string) types.Oncut {
	return types.Oncut{IAttribute: attrs.Oncut(value)}
}

// Ondblclick
//
// Element(s): HTML elements.
//
// Description: dblclick event handler.
//
// Value: Event handler content attribute.
func Ondblclick(value string) types.Ondblclick {
	return types.Ondblclick{IAttribute: attrs.Ondblclick(value)}
}

// Ondrag
//
// Element(s): HTML elements.
//
// Description: drag event handler.
//
// Value: Event handler content attribute.
func Ondrag(value string) types.Ondrag {
	return types.Ondrag{IAttribute: attrs.Ondrag(value)}
}

// Ondragend
//
// Element(s): HTML elements.
//
// Description: dragend event handler.
//
// Value: Event handler content attribute.
func Ondragend(value string) types.Ondragend {
	return types.Ondragend{IAttribute: attrs.Ondragend(value)}
}

// Ondragenter
//
// Element(s): HTML elements.
//
// Description: dragenter event handler.
//
// Value: Event handler content attribute.
func Ondragenter(value string) types.Ondragenter {
	return types.Ondragenter{IAttribute: attrs.Ondragenter(value)}
}

// Ondragleave
//
// Element(s): HTML elements.
//
// Description: dragleave event handler.
//
// Value: Event handler content attribute.
func Ondragleave(value string) types.Ondragleave {
	return types.Ondragleave{IAttribute: attrs.Ondragleave(value)}
}

// Ondragover
//
// Element(s): HTML elements.
//
// Description: dragover event handler.
//
// Value: Event handler content attribute.
func Ondragover(value string) types.Ondragover {
	return types.Ondragover{IAttribute: attrs.Ondragover(value)}
}

// Ondragstart
//
// Element(s): HTML elements.
//
// Description: dragstart event handler.
//
// Value: Event handler content attribute.
func Ondragstart(value string) types.Ondragstart {
	return types.Ondragstart{IAttribute: attrs.Ondragstart(value)}
}

// Ondrop
//
// Element(s): HTML elements.
//
// Description: drop event handler.
//
// Value: Event handler content attribute.
func Ondrop(value string) types.Ondrop {
	return types.Ondrop{IAttribute: attrs.Ondrop(value)}
}

// Ondurationchange
//
// Element(s): HTML elements.
//
// Description: durationchange event handler.
//
// Value: Event handler content attribute.
func Ondurationchange(value string) types.Ondurationchange {
	return types.Ondurationchange{IAttribute: attrs.Ondurationchange(value)}
}

// Onemptied
//
// Element(s): HTML elements.
//
// Description: emptied event handler.
//
// Value: Event handler content attribute.
func Onemptied(value string) types.Onemptied {
	return types.Onemptied{IAttribute: attrs.Onemptied(value)}
}

// Onended
//
// Element(s): HTML elements.
//
// Description: ended event handler.
//
// Value: Event handler content attribute.
func Onended(value string) types.Onended {
	return types.Onended{IAttribute: attrs.Onended(value)}
}

// Onerror
//
// Element(s): HTML elements.
//
// Description: error event handler.
//
// Value: Event handler content attribute.
func Onerror(value string) types.Onerror {
	return types.Onerror{IAttribute: attrs.Onerror(value)}
}

// Onfocus
//
// Element(s): HTML elements.
//
// Description: focus event handler.
//
// Value: Event handler content attribute.
func Onfocus(value string) types.Onfocus {
	return types.Onfocus{IAttribute: attrs.Onfocus(value)}
}

// Onformdata
//
// Element(s): HTML elements.
//
// Description: formdata event handler.
//
// Value: Event handler content attribute.
func Onformdata(value string) types.Onformdata {
	return types.Onformdata{IAttribute: attrs.Onformdata(value)}
}

// Onhashchange
//
// Element(s): body.
//
// Description: hashchange event handler for Window object.
//
// Value: Event handler content attribute.
func Onhashchange(value string) types.Onhashchange {
	return types.Onhashchange{IAttribute: attrs.Onhashchange(value)}
}

// Oninput
//
// Element(s): HTML elements.
//
// Description: input event handler.
//
// Value: Event handler content attribute.
func Oninput(value string) types.Oninput {
	return types.Oninput{IAttribute: attrs.Oninput(value)}
}

// Oninvalid
//
// Element(s): HTML elements.
//
// Description: invalid event handler.
//
// Value: Event handler content attribute.
func Oninvalid(value string) types.Oninvalid {
	return types.Oninvalid{IAttribute: attrs.Oninvalid(value)}
}

// Onkeydown
//
// Element(s): HTML elements.
//
// Description: keydown event handler.
//
// Value: Event handler content attribute.
func Onkeydown(value string) types.Onkeydown {
	return types.Onkeydown{IAttribute: attrs.Onkeydown(value)}
}

// Onkeypress
//
// Element(s): HTML elements.
//
// Description: keypress event handler.
//
// Value: Event handler content attribute.
func Onkeypress(value string) types.Onkeypress {
	return types.Onkeypress{IAttribute: attrs.Onkeypress(value)}
}

// Onkeyup
//
// Element(s): HTML elements.
//
// Description: keyup event handler.
//
// Value: Event handler content attribute.
func Onkeyup(value string) types.Onkeyup {
	return types.Onkeyup{IAttribute: attrs.Onkeyup(value)}
}

// Onlanguagechange
//
// Element(s): body.
//
// Description: languagechange event handler for Window object.
//
// Value: Event handler content attribute.
func Onlanguagechange(value string) types.Onlanguagechange {
	return types.Onlanguagechange{IAttribute: attrs.Onlanguagechange(value)}
}

// Onload
//
// Element(s): HTML elements.
//
// Description: load event handler.
//
// Value: Event handler content attribute.
func Onload(value string) types.Onload {
	return types.Onload{IAttribute: attrs.Onload(value)}
}

// Onloadeddata
//
// Element(s): HTML elements.
//
// Description: loadeddata event handler.
//
// Value: Event handler content attribute.
func Onloadeddata(value string) types.Onloadeddata {
	return types.Onloadeddata{IAttribute: attrs.Onloadeddata(value)}
}

// Onloadedmetadata
//
// Element(s): HTML elements.
//
// Description: loadedmetadata event handler.
//
// Value: Event handler content attribute.
func Onloadedmetadata(value string) types.Onloadedmetadata {
	return types.Onloadedmetadata{IAttribute: attrs.Onloadedmetadata(value)}
}

// Onloadstart
//
// Element(s): HTML elements.
//
// Description: loadstart event handler.
//
// Value: Event handler content attribute.
func Onloadstart(value string) types.Onloadstart {
	return types.Onloadstart{IAttribute: attrs.Onloadstart(value)}
}

// Onmessage
//
// Element(s): body.
//
// Description: message event handler for Window object.
//
// Value: Event handler content attribute.
func Onmessage(value string) types.Onmessage {
	return types.Onmessage{IAttribute: attrs.Onmessage(value)}
}

// Onmessageerror
//
// Element(s): body.
//
// Description: messageerror event handler for Window object.
//
// Value: Event handler content attribute.
func Onmessageerror(value string) types.Onmessageerror {
	return types.Onmessageerror{IAttribute: attrs.Onmessageerror(value)}
}

// Onmousedown
//
// Element(s): HTML elements.
//
// Description: mousedown event handler.
//
// Value: Event handler content attribute.
func Onmousedown(value string) types.Onmousedown {
	return types.Onmousedown{IAttribute: attrs.Onmousedown(value)}
}

// Onmouseenter
//
// Element(s): HTML elements.
//
// Description: mouseenter event handler.
//
// Value: Event handler content attribute.
func Onmouseenter(value string) types.Onmouseenter {
	return types.Onmouseenter{IAttribute: attrs.Onmouseenter(value)}
}

// Onmouseleave
//
// Element(s): HTML elements.
//
// Description: mouseleave event handler.
//
// Value: Event handler content attribute.
func Onmouseleave(value string) types.Onmouseleave {
	return types.Onmouseleave{IAttribute: attrs.Onmouseleave(value)}
}

// Onmousemove
//
// Element(s): HTML elements.
//
// Description: mousemove event handler.
//
// Value: Event handler content attribute.
func Onmousemove(value string) types.Onmousemove {
	return types.Onmousemove{IAttribute: attrs.Onmousemove(value)}
}

// Onmouseout
//
// Element(s): HTML elements.
//
// Description: mouseout event handler.
//
// Value: Event handler content attribute.
func Onmouseout(value string) types.Onmouseout {
	return types.Onmouseout{IAttribute: attrs.Onmouseout(value)}
}

// Onmouseover
//
// Element(s): HTML elements.
//
// Description: mouseover event handler.
//
// Value: Event handler content attribute.
func Onmouseover(value string) types.Onmouseover {
	return types.Onmouseover{IAttribute: attrs.Onmouseover(value)}
}

// Onmouseup
//
// Element(s): HTML elements.
//
// Description: mouseup event handler.
//
// Value: Event handler content attribute.
func Onmouseup(value string) types.Onmouseup {
	return types.Onmouseup{IAttribute: attrs.Onmouseup(value)}
}

// Onoffline
//
// Element(s): body.
//
// Description: offline event handler for Window object.
//
// Value: Event handler content attribute.
func Onoffline(value string) types.Onoffline {
	return types.Onoffline{IAttribute: attrs.Onoffline(value)}
}

// Ononline
//
// Element(s): body.
//
// Description: online event handler for Window object.
//
// Value: Event handler content attribute.
func Ononline(value string) types.Ononline {
	return types.Ononline{IAttribute: attrs.Ononline(value)}
}

// Onpagehide
//
// Element(s): body.
//
// Description: pagehide event handler for Window object.
//
// Value: Event handler content attribute.
func Onpagehide(value string) types.Onpagehide {
	return types.Onpagehide{IAttribute: attrs.Onpagehide(value)}
}

// Onpagereveal
//
// Element(s): body.
//
// Description: pagereveal event handler for Window object.
//
// Value: Event handler content attribute.
func Onpagereveal(value string) types.Onpagereveal {
	return types.Onpagereveal{IAttribute: attrs.Onpagereveal(value)}
}

// Onpageshow
//
// Element(s): body.
//
// Description: pageshow event handler for Window object.
//
// Value: Event handler content attribute.
func Onpageshow(value string) types.Onpageshow {
	return types.Onpageshow{IAttribute: attrs.Onpageshow(value)}
}

// Onpageswap
//
// Element(s): body.
//
// Description: pageswap event handler for Window object.
//
// Value: Event handler content attribute.
func Onpageswap(value string) types.Onpageswap {
	return types.Onpageswap{IAttribute: attrs.Onpageswap(value)}
}

// Onpaste
//
// Element(s): HTML elements.
//
// Description: paste event handler.
//
// Value: Event handler content attribute.
func Onpaste(value string) types.Onpaste {
	return types.Onpaste{IAttribute: attrs.Onpaste(value)}
}

// Onpause
//
// Element(s): HTML elements.
//
// Description: pause event handler.
//
// Value: Event handler content attribute.
func Onpause(value string) types.Onpause {
	return types.Onpause{IAttribute: attrs.Onpause(value)}
}

// Onplay
//
// Element(s): HTML elements.
//
// Description: play event handler.
//
// Value: Event handler content attribute.
func Onplay(value string) types.Onplay {
	return types.Onplay{IAttribute: attrs.Onplay(value)}
}

// Onplaying
//
// Element(s): HTML elements.
//
// Description: playing event handler.
//
// Value: Event handler content attribute.
func Onplaying(value string) types.Onplaying {
	return types.Onplaying{IAttribute: attrs.Onplaying(value)}
}

// Onpopstate
//
// Element(s): body.
//
// Description: popstate event handler for Window object.
//
// Value: Event handler content attribute.
func Onpopstate(value string) types.Onpopstate {
	return types.Onpopstate{IAttribute: attrs.Onpopstate(value)}
}

// Onprogress
//
// Element(s): HTML elements.
//
// Description: progress event handler.
//
// Value: Event handler content attribute.
func Onprogress(value string) types.Onprogress {
	return types.Onprogress{IAttribute: attrs.Onprogress(value)}
}

// Onratechange
//
// Element(s): HTML elements.
//
// Description: ratechange event handler.
//
// Value: Event handler content attribute.
func Onratechange(value string) types.Onratechange {
	return types.Onratechange{IAttribute: attrs.Onratechange(value)}
}

// Onreset
//
// Element(s): HTML elements.
//
// Description: reset event handler.
//
// Value: Event handler content attribute.
func Onreset(value string) types.Onreset {
	return types.Onreset{IAttribute: attrs.Onreset(value)}
}

// Onresize
//
// Element(s): HTML elements.
//
// Description: resize event handler.
//
// Value: Event handler content attribute.
func Onresize(value string) types.Onresize {
	return types.Onresize{IAttribute: attrs.Onresize(value)}
}

// Onrejectionhandled
//
// Element(s): body.
//
// Description: rejectionhandled event handler for Window object.
//
// Value: Event handler content attribute.
func Onrejectionhandled(value string) types.Onrejectionhandled {
	return types.Onrejectionhandled{IAttribute: attrs.Onrejectionhandled(value)}
}

// Onscroll
//
// Element(s): HTML elements.
//
// Description: scroll event handler.
//
// Value: Event handler content attribute.
func Onscroll(value string) types.Onscroll {
	return types.Onscroll{IAttribute: attrs.Onscroll(value)}
}

// Onscrollend
//
// Element(s): HTML elements.
//
// Description: scrollend event handler.
//
// Value: Event handler content attribute.
func Onscrollend(value string) types.Onscrollend {
	return types.Onscrollend{IAttribute: attrs.Onscrollend(value)}
}

// Onsecuritypolicyviolation
//
// Element(s): HTML elements.
//
// Description: securitypolicyviolation event handler.
//
// Value: Event handler content attribute.
func Onsecuritypolicyviolation(value string) types.Onsecuritypolicyviolation {
	return types.Onsecuritypolicyviolation{IAttribute: attrs.Onsecuritypolicyviolation(value)}
}

// Onseeked
//
// Element(s): HTML elements.
//
// Description: seeked event handler.
//
// Value: Event handler content attribute.
func Onseeked(value string) types.Onseeked {
	return types.Onseeked{IAttribute: attrs.Onseeked(value)}
}

// Onseeking
//
// Element(s): HTML elements.
//
// Description: seeking event handler.
//
// Value: Event handler content attribute.
func Onseeking(value string) types.Onseeking {
	return types.Onseeking{IAttribute: attrs.Onseeking(value)}
}

// Onselect
//
// Element(s): HTML elements.
//
// Description: select event handler.
//
// Value: Event handler content attribute.
func Onselect(value string) types.Onselect {
	return types.Onselect{IAttribute: attrs.Onselect(value)}
}

// Onslotchange
//
// Element(s): HTML elements.
//
// Description: slotchange event handler.
//
// Value: Event handler content attribute.
func Onslotchange(value string) types.Onslotchange {
	return types.Onslotchange{IAttribute: attrs.Onslotchange(value)}
}

// Onstalled
//
// Element(s): HTML elements.
//
// Description: stalled event handler.
//
// Value: Event handler content attribute.
func Onstalled(value string) types.Onstalled {
	return types.Onstalled{IAttribute: attrs.Onstalled(value)}
}

// Onstorage
//
// Element(s): body.
//
// Description: storage event handler for Window object.
//
// Value: Event handler content attribute.
func Onstorage(value string) types.Onstorage {
	return types.Onstorage{IAttribute: attrs.Onstorage(value)}
}

// Onsubmit
//
// Element(s): HTML elements.
//
// Description: submit event handler.
//
// Value: Event handler content attribute.
func Onsubmit(value string) types.Onsubmit {
	return types.Onsubmit{IAttribute: attrs.Onsubmit(value)}
}

// Onsuspend
//
// Element(s): HTML elements.
//
// Description: suspend event handler.
//
// Value: Event handler content attribute.
func Onsuspend(value string) types.Onsuspend {
	return types.Onsuspend{IAttribute: attrs.Onsuspend(value)}
}

// Ontimeupdate
//
// Element(s): HTML elements.
//
// Description: timeupdate event handler.
//
// Value: Event handler content attribute.
func Ontimeupdate(value string) types.Ontimeupdate {
	return types.Ontimeupdate{IAttribute: attrs.Ontimeupdate(value)}
}

// Ontoggle
//
// Element(s): HTML elements.
//
// Description: toggle event handler.
//
// Value: Event handler content attribute.
func Ontoggle(value string) types.Ontoggle {
	return types.Ontoggle{IAttribute: attrs.Ontoggle(value)}
}

// Onunhandledrejection
//
// Element(s): body.
//
// Description: unhandledrejection event handler for Window object.
//
// Value: Event handler content attribute.
func Onunhandledrejection(value string) types.Onunhandledrejection {
	return types.Onunhandledrejection{IAttribute: attrs.Onunhandledrejection(value)}
}

// Onunload
//
// Element(s): body.
//
// Description: unload event handler for Window object.
//
// Value: Event handler content attribute.
func Onunload(value string) types.Onunload {
	return types.Onunload{IAttribute: attrs.Onunload(value)}
}

// Onvolumechange
//
// Element(s): HTML elements.
//
// Description: volumechange event handler.
//
// Value: Event handler content attribute.
func Onvolumechange(value string) types.Onvolumechange {
	return types.Onvolumechange{IAttribute: attrs.Onvolumechange(value)}
}

// Onwaiting
//
// Element(s): HTML elements.
//
// Description: waiting event handler.
//
// Value: Event handler content attribute.
func Onwaiting(value string) types.Onwaiting {
	return types.Onwaiting{IAttribute: attrs.Onwaiting(value)}
}

// Onwheel
//
// Element(s): HTML elements.
//
// Description: wheel event handler.
//
// Value: Event handler content attribute.
func Onwheel(value string) types.Onwheel {
	return types.Onwheel{IAttribute: attrs.Onwheel(value)}
}
