// Code generated by "go run -C ../../generate ./"; DO NOT EDIT.
// HTML spec at https://html.spec.whatwg.org/multipage/indices.html

package elems

import "github.com/ramonpetgrave64/go-html-compose/pkg/doc"

// GlobalAttribute can be used with any element.
type GlobalAttribute interface {
	doc.IAttribute
	isGlobalAttribute()
	isAAttribute()
	isAbbrAttribute()
	isAddressAttribute()
	isAreaAttribute()
	isArticleAttribute()
	isAsideAttribute()
	isAudioAttribute()
	isBAttribute()
	isBaseAttribute()
	isBdiAttribute()
	isBdoAttribute()
	isBlockquoteAttribute()
	isBodyAttribute()
	isBrAttribute()
	isButtonAttribute()
	isCanvasAttribute()
	isCaptionAttribute()
	isCiteAttribute()
	isCodeAttribute()
	isColAttribute()
	isColgroupAttribute()
	isDataAttribute()
	isDatalistAttribute()
	isDdAttribute()
	isDelAttribute()
	isDetailsAttribute()
	isDfnAttribute()
	isDialogAttribute()
	isDivAttribute()
	isDlAttribute()
	isDtAttribute()
	isEmAttribute()
	isEmbedAttribute()
	isFieldsetAttribute()
	isFigcaptionAttribute()
	isFigureAttribute()
	isFooterAttribute()
	isFormAttribute()
	isH1Attribute()
	isH2Attribute()
	isH3Attribute()
	isH4Attribute()
	isH5Attribute()
	isH6Attribute()
	isHeadAttribute()
	isHeaderAttribute()
	isHgroupAttribute()
	isHrAttribute()
	isHtmlAttribute()
	isIAttribute()
	isIframeAttribute()
	isImgAttribute()
	isInputAttribute()
	isInsAttribute()
	isKbdAttribute()
	isLabelAttribute()
	isLegendAttribute()
	isLiAttribute()
	isLinkAttribute()
	isMainAttribute()
	isMapAttribute()
	isMarkAttribute()
	isMathAttribute()
	isMenuAttribute()
	isMetaAttribute()
	isMeterAttribute()
	isNavAttribute()
	isNoscriptAttribute()
	isObjectAttribute()
	isOlAttribute()
	isOptgroupAttribute()
	isOptionAttribute()
	isOutputAttribute()
	isPAttribute()
	isPictureAttribute()
	isPreAttribute()
	isProgressAttribute()
	isQAttribute()
	isRpAttribute()
	isRtAttribute()
	isRubyAttribute()
	isSAttribute()
	isSampAttribute()
	isScriptAttribute()
	isSearchAttribute()
	isSectionAttribute()
	isSelectAttribute()
	isSelectedcontentAttribute()
	isSlotAttribute()
	isSmallAttribute()
	isSourceAttribute()
	isSpanAttribute()
	isStrongAttribute()
	isStyleAttribute()
	isSubAttribute()
	isSummaryAttribute()
	isSupAttribute()
	isSvgAttribute()
	isTableAttribute()
	isTbodyAttribute()
	isTdAttribute()
	isTemplateAttribute()
	isTextareaAttribute()
	isTfootAttribute()
	isThAttribute()
	isTheadAttribute()
	isTimeAttribute()
	isTitleAttribute()
	isTrAttribute()
	isTrackAttribute()
	isUAttribute()
	isUlAttribute()
	isVarAttribute()
	isVideoAttribute()
	isWbrAttribute()
}

// Attribute types for specific elements
type (
	// AAttribute is an attribute that can be used with the a element.
	AAttribute interface {
		doc.IAttribute
		isAAttribute()
	}
	
	// AbbrAttribute is an attribute that can be used with the abbr element.
	AbbrAttribute interface {
		doc.IAttribute
		isAbbrAttribute()
	}
	
	// AddressAttribute is an attribute that can be used with the address element.
	AddressAttribute interface {
		doc.IAttribute
		isAddressAttribute()
	}
	
	// AreaAttribute is an attribute that can be used with the area element.
	AreaAttribute interface {
		doc.IAttribute
		isAreaAttribute()
	}
	
	// ArticleAttribute is an attribute that can be used with the article element.
	ArticleAttribute interface {
		doc.IAttribute
		isArticleAttribute()
	}
	
	// AsideAttribute is an attribute that can be used with the aside element.
	AsideAttribute interface {
		doc.IAttribute
		isAsideAttribute()
	}
	
	// AudioAttribute is an attribute that can be used with the audio element.
	AudioAttribute interface {
		doc.IAttribute
		isAudioAttribute()
	}
	
	// BAttribute is an attribute that can be used with the b element.
	BAttribute interface {
		doc.IAttribute
		isBAttribute()
	}
	
	// BaseAttribute is an attribute that can be used with the base element.
	BaseAttribute interface {
		doc.IAttribute
		isBaseAttribute()
	}
	
	// BdiAttribute is an attribute that can be used with the bdi element.
	BdiAttribute interface {
		doc.IAttribute
		isBdiAttribute()
	}
	
	// BdoAttribute is an attribute that can be used with the bdo element.
	BdoAttribute interface {
		doc.IAttribute
		isBdoAttribute()
	}
	
	// BlockquoteAttribute is an attribute that can be used with the blockquote element.
	BlockquoteAttribute interface {
		doc.IAttribute
		isBlockquoteAttribute()
	}
	
	// BodyAttribute is an attribute that can be used with the body element.
	BodyAttribute interface {
		doc.IAttribute
		isBodyAttribute()
	}
	
	// BrAttribute is an attribute that can be used with the br element.
	BrAttribute interface {
		doc.IAttribute
		isBrAttribute()
	}
	
	// ButtonAttribute is an attribute that can be used with the button element.
	ButtonAttribute interface {
		doc.IAttribute
		isButtonAttribute()
	}
	
	// CanvasAttribute is an attribute that can be used with the canvas element.
	CanvasAttribute interface {
		doc.IAttribute
		isCanvasAttribute()
	}
	
	// CaptionAttribute is an attribute that can be used with the caption element.
	CaptionAttribute interface {
		doc.IAttribute
		isCaptionAttribute()
	}
	
	// CiteAttribute is an attribute that can be used with the cite element.
	CiteAttribute interface {
		doc.IAttribute
		isCiteAttribute()
	}
	
	// CodeAttribute is an attribute that can be used with the code element.
	CodeAttribute interface {
		doc.IAttribute
		isCodeAttribute()
	}
	
	// ColAttribute is an attribute that can be used with the col element.
	ColAttribute interface {
		doc.IAttribute
		isColAttribute()
	}
	
	// ColgroupAttribute is an attribute that can be used with the colgroup element.
	ColgroupAttribute interface {
		doc.IAttribute
		isColgroupAttribute()
	}
	
	// DataAttribute is an attribute that can be used with the data element.
	DataAttribute interface {
		doc.IAttribute
		isDataAttribute()
	}
	
	// DatalistAttribute is an attribute that can be used with the datalist element.
	DatalistAttribute interface {
		doc.IAttribute
		isDatalistAttribute()
	}
	
	// DdAttribute is an attribute that can be used with the dd element.
	DdAttribute interface {
		doc.IAttribute
		isDdAttribute()
	}
	
	// DelAttribute is an attribute that can be used with the del element.
	DelAttribute interface {
		doc.IAttribute
		isDelAttribute()
	}
	
	// DetailsAttribute is an attribute that can be used with the details element.
	DetailsAttribute interface {
		doc.IAttribute
		isDetailsAttribute()
	}
	
	// DfnAttribute is an attribute that can be used with the dfn element.
	DfnAttribute interface {
		doc.IAttribute
		isDfnAttribute()
	}
	
	// DialogAttribute is an attribute that can be used with the dialog element.
	DialogAttribute interface {
		doc.IAttribute
		isDialogAttribute()
	}
	
	// DivAttribute is an attribute that can be used with the div element.
	DivAttribute interface {
		doc.IAttribute
		isDivAttribute()
	}
	
	// DlAttribute is an attribute that can be used with the dl element.
	DlAttribute interface {
		doc.IAttribute
		isDlAttribute()
	}
	
	// DtAttribute is an attribute that can be used with the dt element.
	DtAttribute interface {
		doc.IAttribute
		isDtAttribute()
	}
	
	// EmAttribute is an attribute that can be used with the em element.
	EmAttribute interface {
		doc.IAttribute
		isEmAttribute()
	}
	
	// EmbedAttribute is an attribute that can be used with the embed element.
	EmbedAttribute interface {
		doc.IAttribute
		isEmbedAttribute()
	}
	
	// FieldsetAttribute is an attribute that can be used with the fieldset element.
	FieldsetAttribute interface {
		doc.IAttribute
		isFieldsetAttribute()
	}
	
	// FigcaptionAttribute is an attribute that can be used with the figcaption element.
	FigcaptionAttribute interface {
		doc.IAttribute
		isFigcaptionAttribute()
	}
	
	// FigureAttribute is an attribute that can be used with the figure element.
	FigureAttribute interface {
		doc.IAttribute
		isFigureAttribute()
	}
	
	// FooterAttribute is an attribute that can be used with the footer element.
	FooterAttribute interface {
		doc.IAttribute
		isFooterAttribute()
	}
	
	// FormAttribute is an attribute that can be used with the form element.
	FormAttribute interface {
		doc.IAttribute
		isFormAttribute()
	}
	
	// H1Attribute is an attribute that can be used with the h1 element.
	H1Attribute interface {
		doc.IAttribute
		isH1Attribute()
	}
	
	// H2Attribute is an attribute that can be used with the h2 element.
	H2Attribute interface {
		doc.IAttribute
		isH2Attribute()
	}
	
	// H3Attribute is an attribute that can be used with the h3 element.
	H3Attribute interface {
		doc.IAttribute
		isH3Attribute()
	}
	
	// H4Attribute is an attribute that can be used with the h4 element.
	H4Attribute interface {
		doc.IAttribute
		isH4Attribute()
	}
	
	// H5Attribute is an attribute that can be used with the h5 element.
	H5Attribute interface {
		doc.IAttribute
		isH5Attribute()
	}
	
	// H6Attribute is an attribute that can be used with the h6 element.
	H6Attribute interface {
		doc.IAttribute
		isH6Attribute()
	}
	
	// HeadAttribute is an attribute that can be used with the head element.
	HeadAttribute interface {
		doc.IAttribute
		isHeadAttribute()
	}
	
	// HeaderAttribute is an attribute that can be used with the header element.
	HeaderAttribute interface {
		doc.IAttribute
		isHeaderAttribute()
	}
	
	// HgroupAttribute is an attribute that can be used with the hgroup element.
	HgroupAttribute interface {
		doc.IAttribute
		isHgroupAttribute()
	}
	
	// HrAttribute is an attribute that can be used with the hr element.
	HrAttribute interface {
		doc.IAttribute
		isHrAttribute()
	}
	
	// HtmlAttribute is an attribute that can be used with the html element.
	HtmlAttribute interface {
		doc.IAttribute
		isHtmlAttribute()
	}
	
	// IAttribute is an attribute that can be used with the i element.
	IAttribute interface {
		doc.IAttribute
		isIAttribute()
	}
	
	// IframeAttribute is an attribute that can be used with the iframe element.
	IframeAttribute interface {
		doc.IAttribute
		isIframeAttribute()
	}
	
	// ImgAttribute is an attribute that can be used with the img element.
	ImgAttribute interface {
		doc.IAttribute
		isImgAttribute()
	}
	
	// InputAttribute is an attribute that can be used with the input element.
	InputAttribute interface {
		doc.IAttribute
		isInputAttribute()
	}
	
	// InsAttribute is an attribute that can be used with the ins element.
	InsAttribute interface {
		doc.IAttribute
		isInsAttribute()
	}
	
	// KbdAttribute is an attribute that can be used with the kbd element.
	KbdAttribute interface {
		doc.IAttribute
		isKbdAttribute()
	}
	
	// LabelAttribute is an attribute that can be used with the label element.
	LabelAttribute interface {
		doc.IAttribute
		isLabelAttribute()
	}
	
	// LegendAttribute is an attribute that can be used with the legend element.
	LegendAttribute interface {
		doc.IAttribute
		isLegendAttribute()
	}
	
	// LiAttribute is an attribute that can be used with the li element.
	LiAttribute interface {
		doc.IAttribute
		isLiAttribute()
	}
	
	// LinkAttribute is an attribute that can be used with the link element.
	LinkAttribute interface {
		doc.IAttribute
		isLinkAttribute()
	}
	
	// MainAttribute is an attribute that can be used with the main element.
	MainAttribute interface {
		doc.IAttribute
		isMainAttribute()
	}
	
	// MapAttribute is an attribute that can be used with the map element.
	MapAttribute interface {
		doc.IAttribute
		isMapAttribute()
	}
	
	// MarkAttribute is an attribute that can be used with the mark element.
	MarkAttribute interface {
		doc.IAttribute
		isMarkAttribute()
	}
	
	// MathAttribute is an attribute that can be used with the math element.
	MathAttribute interface {
		doc.IAttribute
		isMathAttribute()
	}
	
	// MenuAttribute is an attribute that can be used with the menu element.
	MenuAttribute interface {
		doc.IAttribute
		isMenuAttribute()
	}
	
	// MetaAttribute is an attribute that can be used with the meta element.
	MetaAttribute interface {
		doc.IAttribute
		isMetaAttribute()
	}
	
	// MeterAttribute is an attribute that can be used with the meter element.
	MeterAttribute interface {
		doc.IAttribute
		isMeterAttribute()
	}
	
	// NavAttribute is an attribute that can be used with the nav element.
	NavAttribute interface {
		doc.IAttribute
		isNavAttribute()
	}
	
	// NoscriptAttribute is an attribute that can be used with the noscript element.
	NoscriptAttribute interface {
		doc.IAttribute
		isNoscriptAttribute()
	}
	
	// ObjectAttribute is an attribute that can be used with the object element.
	ObjectAttribute interface {
		doc.IAttribute
		isObjectAttribute()
	}
	
	// OlAttribute is an attribute that can be used with the ol element.
	OlAttribute interface {
		doc.IAttribute
		isOlAttribute()
	}
	
	// OptgroupAttribute is an attribute that can be used with the optgroup element.
	OptgroupAttribute interface {
		doc.IAttribute
		isOptgroupAttribute()
	}
	
	// OptionAttribute is an attribute that can be used with the option element.
	OptionAttribute interface {
		doc.IAttribute
		isOptionAttribute()
	}
	
	// OutputAttribute is an attribute that can be used with the output element.
	OutputAttribute interface {
		doc.IAttribute
		isOutputAttribute()
	}
	
	// PAttribute is an attribute that can be used with the p element.
	PAttribute interface {
		doc.IAttribute
		isPAttribute()
	}
	
	// PictureAttribute is an attribute that can be used with the picture element.
	PictureAttribute interface {
		doc.IAttribute
		isPictureAttribute()
	}
	
	// PreAttribute is an attribute that can be used with the pre element.
	PreAttribute interface {
		doc.IAttribute
		isPreAttribute()
	}
	
	// ProgressAttribute is an attribute that can be used with the progress element.
	ProgressAttribute interface {
		doc.IAttribute
		isProgressAttribute()
	}
	
	// QAttribute is an attribute that can be used with the q element.
	QAttribute interface {
		doc.IAttribute
		isQAttribute()
	}
	
	// RpAttribute is an attribute that can be used with the rp element.
	RpAttribute interface {
		doc.IAttribute
		isRpAttribute()
	}
	
	// RtAttribute is an attribute that can be used with the rt element.
	RtAttribute interface {
		doc.IAttribute
		isRtAttribute()
	}
	
	// RubyAttribute is an attribute that can be used with the ruby element.
	RubyAttribute interface {
		doc.IAttribute
		isRubyAttribute()
	}
	
	// SAttribute is an attribute that can be used with the s element.
	SAttribute interface {
		doc.IAttribute
		isSAttribute()
	}
	
	// SampAttribute is an attribute that can be used with the samp element.
	SampAttribute interface {
		doc.IAttribute
		isSampAttribute()
	}
	
	// ScriptAttribute is an attribute that can be used with the script element.
	ScriptAttribute interface {
		doc.IAttribute
		isScriptAttribute()
	}
	
	// SearchAttribute is an attribute that can be used with the search element.
	SearchAttribute interface {
		doc.IAttribute
		isSearchAttribute()
	}
	
	// SectionAttribute is an attribute that can be used with the section element.
	SectionAttribute interface {
		doc.IAttribute
		isSectionAttribute()
	}
	
	// SelectAttribute is an attribute that can be used with the select element.
	SelectAttribute interface {
		doc.IAttribute
		isSelectAttribute()
	}
	
	// SelectedcontentAttribute is an attribute that can be used with the selectedcontent element.
	SelectedcontentAttribute interface {
		doc.IAttribute
		isSelectedcontentAttribute()
	}
	
	// SlotAttribute is an attribute that can be used with the slot element.
	SlotAttribute interface {
		doc.IAttribute
		isSlotAttribute()
	}
	
	// SmallAttribute is an attribute that can be used with the small element.
	SmallAttribute interface {
		doc.IAttribute
		isSmallAttribute()
	}
	
	// SourceAttribute is an attribute that can be used with the source element.
	SourceAttribute interface {
		doc.IAttribute
		isSourceAttribute()
	}
	
	// SpanAttribute is an attribute that can be used with the span element.
	SpanAttribute interface {
		doc.IAttribute
		isSpanAttribute()
	}
	
	// StrongAttribute is an attribute that can be used with the strong element.
	StrongAttribute interface {
		doc.IAttribute
		isStrongAttribute()
	}
	
	// StyleAttribute is an attribute that can be used with the style element.
	StyleAttribute interface {
		doc.IAttribute
		isStyleAttribute()
	}
	
	// SubAttribute is an attribute that can be used with the sub element.
	SubAttribute interface {
		doc.IAttribute
		isSubAttribute()
	}
	
	// SummaryAttribute is an attribute that can be used with the summary element.
	SummaryAttribute interface {
		doc.IAttribute
		isSummaryAttribute()
	}
	
	// SupAttribute is an attribute that can be used with the sup element.
	SupAttribute interface {
		doc.IAttribute
		isSupAttribute()
	}
	
	// SvgAttribute is an attribute that can be used with the svg element.
	SvgAttribute interface {
		doc.IAttribute
		isSvgAttribute()
	}
	
	// TableAttribute is an attribute that can be used with the table element.
	TableAttribute interface {
		doc.IAttribute
		isTableAttribute()
	}
	
	// TbodyAttribute is an attribute that can be used with the tbody element.
	TbodyAttribute interface {
		doc.IAttribute
		isTbodyAttribute()
	}
	
	// TdAttribute is an attribute that can be used with the td element.
	TdAttribute interface {
		doc.IAttribute
		isTdAttribute()
	}
	
	// TemplateAttribute is an attribute that can be used with the template element.
	TemplateAttribute interface {
		doc.IAttribute
		isTemplateAttribute()
	}
	
	// TextareaAttribute is an attribute that can be used with the textarea element.
	TextareaAttribute interface {
		doc.IAttribute
		isTextareaAttribute()
	}
	
	// TfootAttribute is an attribute that can be used with the tfoot element.
	TfootAttribute interface {
		doc.IAttribute
		isTfootAttribute()
	}
	
	// ThAttribute is an attribute that can be used with the th element.
	ThAttribute interface {
		doc.IAttribute
		isThAttribute()
	}
	
	// TheadAttribute is an attribute that can be used with the thead element.
	TheadAttribute interface {
		doc.IAttribute
		isTheadAttribute()
	}
	
	// TimeAttribute is an attribute that can be used with the time element.
	TimeAttribute interface {
		doc.IAttribute
		isTimeAttribute()
	}
	
	// TitleAttribute is an attribute that can be used with the title element.
	TitleAttribute interface {
		doc.IAttribute
		isTitleAttribute()
	}
	
	// TrAttribute is an attribute that can be used with the tr element.
	TrAttribute interface {
		doc.IAttribute
		isTrAttribute()
	}
	
	// TrackAttribute is an attribute that can be used with the track element.
	TrackAttribute interface {
		doc.IAttribute
		isTrackAttribute()
	}
	
	// UAttribute is an attribute that can be used with the u element.
	UAttribute interface {
		doc.IAttribute
		isUAttribute()
	}
	
	// UlAttribute is an attribute that can be used with the ul element.
	UlAttribute interface {
		doc.IAttribute
		isUlAttribute()
	}
	
	// VarAttribute is an attribute that can be used with the var element.
	VarAttribute interface {
		doc.IAttribute
		isVarAttribute()
	}
	
	// VideoAttribute is an attribute that can be used with the video element.
	VideoAttribute interface {
		doc.IAttribute
		isVideoAttribute()
	}
	
	// WbrAttribute is an attribute that can be used with the wbr element.
	WbrAttribute interface {
		doc.IAttribute
		isWbrAttribute()
	}
)